[package]
name = "snapcompact"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
fontdue.workspace = true
heapless.workspace = true
inferno.workspace = true
napi.workspace = true
napi-derive.workspace = true
parking_lot.workspace = true
png.workspace = true
serde.workspace = true
smallvec.workspace = true
tokio.workspace = true

[dev-dependencies]
fancy-regex.workspace = true
libc.workspace = true
tiktoken-rs.workspace = true
