// ── Event types ───────────────────────────────────────────────────────────

import type { InferenceMode } from "../configuration/inference-modes.ts";
import type {
	ExplicitTaskState,
	TaskPhase,
} from "../tasks/task-state-controller.ts";
import type { Message, MessageRole, StopReason } from "./types-messages.ts";
import type { HarnessIntervention } from "../intervention-controller.ts";

/**
 * Envelope metadata stamped onto every event at the emit boundary: a
 * monotonic per-loop sequence number and a wall-clock timestamp.
 */
export interface AgentEventEnvelope {
	seq?: number;
	ts?: number;
}

export type AgentEventBody =
	| { type: "agent_start" }
	| ({ type: "harness_intervention" } & HarnessIntervention)
	| { type: "agent_end"; messages?: Message[] }
	| { type: "agent_settled"; nextTurnCount?: number }
	| {
			type: "run_outcome";
			status: "completed" | "needs_input" | "blocked" | "failed" | "cancelled";
			summary?: string;
			source: "structured" | "heuristic" | "runtime";
	  }
	| {
			type: "queue_update";
			steering: readonly string[];
			followUp: readonly string[];
			nextTurn: readonly string[];
	  }
	| { type: "turn_start"; turnId: string }
	| { type: "task_state_update"; state: ExplicitTaskState }
	| {
			type: "inference_mode_selected";
			configuredMode: "auto";
			effectiveMode: Exclude<InferenceMode, "auto">;
			reason: string;
			phase: TaskPhase;
	  }
	| {
			type: "turn_end";
			turnId: string;
			stopReason?: StopReason;
			message?: Message;
			toolResults?: Message[];
	  }
	| { type: "message_start"; turnId: string; role: MessageRole }
	| { type: "text_start"; turnId: string }
	| { type: "text_delta"; turnId: string; delta: string }
	| { type: "text_end"; turnId: string }
	| { type: "message_update"; turnId: string; message: Message }
	| { type: "message_end"; turnId: string; message?: Message }
	| {
			type: "context_update";
			tokens: number;
			maxTokens?: number;
			compacted?: boolean;
			/** null means the provider supplied no cache telemetry. */
			cachedTokens?: number | null;
			/** Tokens sent to the provider (prompt/input); null means unavailable. */
			promptTokens?: number | null;
			/** Tokens generated by the provider (completion/output); null means unavailable. */
			completionTokens?: number | null;
	  }
	| {
			type: "compaction";
			reason: "manual" | "context_full" | "auto" | "overflow" | "threshold";
			tokensBefore?: number;
			tokensAfter?: number;
	  }
	| { type: "thinking_delta"; turnId?: string; delta: string }
	| {
			type: "tool_call_start";
			toolName: string;
			toolCallId: string;
			args: string;
	  }
	| {
			type: "tool_call_delta";
			toolCallId: string;
			delta: string;
	  }
	| {
			type: "tool_call_id_update";
			previousToolCallId: string;
			toolCallId: string;
	  }
	| {
			type: "tool_call_end";
			toolName: string;
			toolCallId: string;
			result: string;
			isError?: boolean;
			details?: Record<string, unknown>;
	  }
	| {
			type: "tool_execution_start";
			toolCallId: string;
			toolName: string;
			args: Record<string, unknown>;
	  }
	| {
			type: "tool_execution_update";
			toolCallId: string;
			toolName: string;
			args: Record<string, unknown>;
			partialResult: string;
	  }
	| {
			type: "tool_execution_end";
			toolCallId: string;
			toolName: string;
			result: string;
			isError: boolean;
	  }
	| {
			type: "repair_nudge";
			turnId?: string;
			repairStage: string;
			toolName?: string;
			message: string;
	  }
	| { type: "phase"; phase: "thinking" | "tool" | "idle" }
	| { type: "model_select"; model: string; index: number }
	| { type: "max_iterations"; iterations: number; limit: number }
	| {
			type: "task_failed";
			reason: string;
			iteration: number;
			lastContent?: string;
	  }
	| {
			type: "loop_detected";
			message: string;
			attempt?: number;
	  }
	| {
			type: "subagent_start";
			agentId: string;
			agent: string;
			task: string;
			/** Position within a spawn_agents batch, if run as part of one. */
			taskIndex?: number;
	  }
	| {
			type: "subagent_event";
			agentId: string;
			event: AgentEvent;
			/** Position within a spawn_agents batch, if run as part of one. */
			taskIndex?: number;
	  }
	| {
			type: "subagent_end";
			agentId: string;
			agent: string;
			result: string;
			isError?: boolean;
			turns?: number;
			/** Position within a spawn_agents batch, if run as part of one. */
			taskIndex?: number;
	  }
	| {
			type: "tool_permission_request";
			toolName: string;
			toolCallId: string;
			args: string;
	  }
	| {
			type: "tool_permission_decision";
			toolName: string;
			toolCallId: string;
			decision: "allow" | "deny" | "always";
			source: "rule" | "mode" | "user" | "hook";
	  }
	| { type: "budget_exhausted"; usedTokens: number; limitTokens: number }
	| { type: "error"; message: string; error?: unknown }
	| {
			type: "model_cycle";
			model: string;
			fromModel: string;
			thinkingLevel?: string;
	  }
	| { type: "thinking_level_changed"; level: string }
	| { type: "thinking_level_clamped"; level: string; reason: string }
	| { type: "tools_update"; toolNames: string[] }
	| {
			type: "abort";
			clearedSteering: readonly string[];
			clearedFollowUp: readonly string[];
			clearedNextTurn: readonly string[];
	  }
	| {
			type: "thinking_loop_detected";
			message: string;
			strategy:
				| "thinking_only"
				| "escalation"
				| "meta_reasoning"
				| "budget_exhausted";
			iteration: number;
	  }
	| {
			type: "guard_triggered";
			guard:
				| "duplicate"
				| "failure"
				| "continuation_nudge"
				| "acceptance_retry"
				| "reflection_retry"
				| "loop_detected"
				| "budget_stop"
				| "follow_up"
				| "policy_continue"
				| "continuation_exhausted";
			message: string;
			toolName?: string;
			iteration: number;
	  }
	| {
			type: "thinking_loop_stats";
			consecutiveThinkingOnly: number;
			totalThinkingTurns: number;
			totalThinkingTokens: number;
			metaReasoningHits: number;
	  }
	| {
			type: "acceptance_start";
			level: string;
			criteriaCount: number;
	  }
	| {
			type: "acceptance_check";
			criterionId: string;
			status: "satisfied" | "failed" | "partial";
			severity: string;
	  }
	| {
			type: "acceptance_verify";
			command: string;
			result: "passed" | "failed" | "skipped";
			summary?: string;
	  }
	| {
			type: "acceptance_complete";
			status: "passed" | "failed" | "timeout";
			report?: Record<string, unknown>;
	  }
	| {
			type: "reflection_start";
			turnId: string;
	  }
	| {
			type: "reflection_end";
			turnId: string;
			assessment: "complete" | "incomplete";
			needsMoreWork: boolean;
			issues: string[];
	  }
	// Session tree entries
	| {
			type: "model_change";
			provider: string;
			modelId: string;
	  }
	| {
			type: "active_tools_change";
			activeToolNames: string[];
	  }
	// Retry / error observability
	| {
			type: "agent_retry_start";
			attempt: number;
			maxRetries: number;
			delayMs: number;
			error: string;
			reason?: "compaction" | "error" | "overflow" | "rate_limit";
	  }
	| {
			type: "agent_retry_end";
			attempt: number;
			success: boolean;
			reason?: "compaction" | "error" | "overflow" | "rate_limit";
	  }
	| {
			type: "agent_error";
			message: string;
			phase: "model" | "tool" | "compaction" | "network" | "other";
			recoverable: boolean;
	  }
	// Session lifecycle
	| {
			type: "session_delete";
			sessionFile: string;
			sessionId: string;
	  };

export type AgentEvent = AgentEventBody & AgentEventEnvelope;
export type EventHandler = (event: AgentEvent) => void;
