/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Incrementally ingests old/new text and computes an exact line diff on a
 * worker thread once both sides finish.
 *
 * Complete lines are observable during ingestion. Only equal leading lines
 * are declared stable before EOF; future input can change Myers alignment
 * after the first mismatch.
 */
export declare class DiffStream {
  /** Create an empty two-sided stream. */
  constructor()
  /** Append a JavaScript text chunk to one side. */
  push(side: DiffSide, chunk: string): DiffStreamProgress
  /** Append a UTF-8 subprocess/file chunk without a JS string conversion. */
  pushBytes(side: DiffSide, chunk: Uint8Array): DiffStreamProgress
  /** Mark one side complete; an unfinished final line then becomes visible. */
  finishSide(side: DiffSide): DiffStreamProgress
  /** Mark one side too large and complete without further ingestion. */
  markTooLarge(side: DiffSide): DiffStreamProgress
  /** Current ingestion state. */
  progress(): DiffStreamProgress
  /** Complete display lines from `from`, excluding newline terminators. */
  lines(side: DiffSide, from: number, limit?: number | undefined | null): Array<string>
  /** Snapshot all ingested text for one side. */
  text(side: DiffSide): string
  /**
   * Read a filesystem path directly into one side on the native worker pool.
   *
   * JavaScript can poll [`DiffStream::progress`] and [`DiffStream::lines`]
   * while this promise is pending; file bytes never need to cross into JS
   * and back into the differ.
   */
  openFile(side: DiffSide, path: string, maxBytes?: number | undefined | null, signal?: unknown | undefined | null): Promise<DiffStreamProgress>
  /** Compute exact Myers runs and unified hunks off the JavaScript thread. */
  finish(context?: number | undefined | null): Promise<DiffStreamResult>
}

/** One edit tool call's streaming session. */
export declare class EditSession {
  /**
   * Open a session. `onPreview` (optional) receives every settled preview
   * batch; batches are delivered one at a time, in generation order.
   */
  constructor(store: EditStore, policy: EditPolicy, onPreview?: ((error: Error | null, batch: EditPreviewBatch) => void) | undefined | null)
  /** Append a raw streamed argument fragment. */
  push(delta: string): void
  /** Replace the buffer with the complete argument JSON (no-delta path). */
  setArgsJson(argsJson: string): void
  /** Arguments are complete; triggers the final untrimmed preview. */
  finish(): void
  /**
   * Stage and apply the finished edit through `writer`. Never rejects for
   * engine failures: those come back as `isError` outcomes carrying the
   * model-facing message.
   */
  apply(request: EditApplyRequest, writer: (error: Error | null, request: EditWriteRequest) => Promise<EditWriteResponse>): Promise<EditApplyOutcome>
  /** Stop the preview pump and release buffers. */
  close(): void
}

/** Session-scoped snapshots, clipboard registers, and the no-op loop guard. */
export declare class EditStore {
  constructor()
  /**
   * Record `text` (any line endings) as the current snapshot of
   * `absolutePath` and return its 4-hex tag.
   */
  recordSnapshot(absolutePath: string, text: string, seenLines?: Array<number> | undefined | null): string
  /**
   * Read `absolutePath` from disk and record it; null when the file is
   * unreadable or larger than 4 MiB.
   */
  recordSnapshotFile(absolutePath: string, seenLines?: Array<number> | undefined | null): string | null
  /** Merge displayed lines into the snapshot tagged `tag`. */
  recordSeenLines(absolutePath: string, tag: string, lines: Array<number>): void
  /**
   * Merge the lines a hashline-formatted `body` displays into the
   * snapshot tagged `tag`.
   */
  recordSeenLinesFromBody(absolutePath: string, tag: string, body: string): void
  /** Latest recorded text for `absolutePath`. */
  headText(absolutePath: string): string | null
  /** Latest recorded tag for `absolutePath`. */
  headHash(absolutePath: string): string | null
  /** Recorded text of `absolutePath` tagged `hash`. */
  byHashText(absolutePath: string, hash: string): string | null
  /**
   * Displayed lines recorded for the snapshot tagged `hash`; null when no
   * provenance was recorded.
   */
  seenLines(absolutePath: string, hash: string): Array<number> | null
  invalidate(absolutePath: string): void
  relocate(from: string, to: string): void
  clear(): void
}

/**
 * Apply ast-grep rewrite rules to matching files; honors `dryRun` and returns
 * a promise.
 */
export declare function astEdit(options: AstReplaceOptions): Promise<AstReplaceResult>

/** One ast-grep match with source range and optional meta-variables. */
export interface AstFindMatch {
  /** Display path of the matching file. */
  path: string
  /** Matched source text. */
  text: string
  /** Start byte offset in the file (UTF-8 byte index). */
  byteStart: number
  /** End byte offset in the file (exclusive UTF-8 byte index). */
  byteEnd: number
  /** 1-based start line. */
  startLine: number
  /** 1-based start column. */
  startColumn: number
  /** 1-based end line. */
  endLine: number
  /** 1-based end column. */
  endColumn: number
  /** Meta-variable name to captured text, when `includeMeta` was enabled. */
  metaVariables?: Record<string, string>
}

/** Options for `astGrep`: patterns, scan scope, and match limits. */
export interface AstFindOptions {
  /** ast-grep patterns to search for (OR across patterns). */
  patterns?: Array<string>
  /** Language override; otherwise inferred from file extension per candidate. */
  lang?: string
  /** Single file or directory to scan (combined with `glob` when set). */
  path?: string
  /** Optional glob filter relative to the search root. */
  glob?: string
  /** Rule selector for multi-rule ast-grep configurations. */
  selector?: string
  /** Pattern strictness; defaults to smart matching when omitted. */
  strictness?: AstMatchStrictness
  /** Maximum matches to return after `offset` (default applies when omitted). */
  limit?: number
  /** Number of leading matches to skip before applying `limit`. */
  offset?: number
  /** When true, include meta-variable bindings per match. */
  includeMeta?: boolean
  /**
   * Reserved for contextual snippets; not used by the current native find
   * path.
   */
  context?: number
  /** Optional cancellation handle (library-specific). */
  signal?: unknown
  /** Wall-clock timeout for the worker task in milliseconds. */
  timeoutMs?: number
}

/** Aggregated search statistics and any parse or compile diagnostics. */
export interface AstFindResult {
  /** Page of matches after sort, offset, and limit. */
  matches: Array<AstFindMatch>
  /** Total matches found before paging (can exceed `matches.length`). */
  totalMatches: number
  /** Distinct files that contained at least one match. */
  filesWithMatches: number
  /** Files examined for the query. */
  filesSearched: number
  /** True when results were truncated by `limit`. */
  limitReached: boolean
  /** Non-fatal parse or pattern errors collected during the run. */
  parseErrors?: Array<string>
}

/**
 * Search source files with ast-grep patterns; returns a promise resolved on a
 * worker thread.
 */
export declare function astGrep(options: AstFindOptions): Promise<AstFindResult>

/**
 * Match ast-grep patterns against an in-memory source string; returns a
 * promise resolved on a worker thread.
 *
 * This is the file-free counterpart to [`ast_grep`]: callers that already hold
 * the source (streaming buffers, generated code, editor contents) avoid a
 * temp-file round trip. `lang` is required since there is no path to infer it
 * from.
 */
export declare function astMatch(options: AstMatchOptions): Promise<AstMatchResult>

/**
 * Options for `astMatch`: run ast-grep patterns against an in-memory source
 * string instead of files on disk.
 */
export interface AstMatchOptions {
  /** Source code to match against (parsed in memory, never read from disk). */
  source: string
  /** Language of `source` (required; e.g. "ts", "tsx", "rust", "python"). */
  lang: string
  /** ast-grep patterns to search for (OR across patterns). */
  patterns: Array<string>
  /** Rule selector for multi-rule ast-grep configurations. */
  selector?: string
  /** Pattern strictness; defaults to smart matching when omitted. */
  strictness?: AstMatchStrictness
  /** Maximum matches to return after `offset` (default applies when omitted). */
  limit?: number
  /** Number of leading matches to skip before applying `limit`. */
  offset?: number
  /** When true, include meta-variable bindings per match. */
  includeMeta?: boolean
  /** Optional cancellation handle (library-specific). */
  signal?: unknown
  /** Wall-clock timeout for the worker task in milliseconds. */
  timeoutMs?: number
}

/** Result of an in-memory `astMatch` run. */
export interface AstMatchResult {
  /** Page of matches after sort, offset, and limit. */
  matches: Array<AstFindMatch>
  /** Total matches found before paging (can exceed `matches.length`). */
  totalMatches: number
  /** True when results were truncated by `limit`. */
  limitReached: boolean
  /** Non-fatal parse or pattern-compile errors collected during the run. */
  parseErrors?: Array<string>
}

/** ast-grep pattern strictness (controls how patterns match syntax). */
export declare const enum AstMatchStrictness {
  /** Match at the concrete syntax tree level. */
  Cst = 'cst',
  /** Balanced default suitable for most searches. */
  Smart = 'smart',
  /** Match at the AST level. */
  Ast = 'ast',
  /** More permissive matching. */
  Relaxed = 'relaxed',
  /** Match structural signatures. */
  Signature = 'signature',
  /** Template-style pattern matching. */
  Template = 'template',
}

/**
 * One textual replacement applied to a file (before/after slice and
 * coordinates).
 */
export interface AstReplaceChange {
  /** File path for this change. */
  path: string
  /** Original matched text. */
  before: string
  /** Replacement text. */
  after: string
  /** Start byte offset of the replaced span. */
  byteStart: number
  /** End byte offset of the replaced span (exclusive). */
  byteEnd: number
  /**
   * Length of deleted text in bytes (may differ from `byteEnd - byteStart`
   * for edge cases).
   */
  deletedLength: number
  /** 1-based start line of the match. */
  startLine: number
  /** 1-based start column. */
  startColumn: number
  /** 1-based end line. */
  endLine: number
  /** 1-based end column. */
  endColumn: number
}

/** Per-file replacement count after an `astEdit` run. */
export interface AstReplaceFileChange {
  /** File that had replacements. */
  path: string
  /** Number of replacements in that file. */
  count: number
}

/**
 * Options for `astEdit`: rewrite rules, scan scope, safety limits, and
 * dry-run.
 */
export interface AstReplaceOptions {
  /** Map of pattern string to replacement template. */
  rewrites?: Record<string, string>
  /**
   * Language override applied to every file; otherwise inferred per file, so
   * mixed-language paths rewrite each file in its own language.
   */
  lang?: string
  /** Single file or directory to rewrite. */
  path?: string
  /** Optional glob filter within the search root. */
  glob?: string
  /** Rule selector for multi-rule configurations. */
  selector?: string
  /** Pattern strictness for rewrites. */
  strictness?: AstMatchStrictness
  /** When true (default), compute changes without writing files. */
  dryRun?: boolean
  /** Cap on replacement applications across all files. */
  maxReplacements?: number
  /** Cap on distinct files that may be modified. */
  maxFiles?: number
  /** Fail the operation when a file cannot be parsed for rewriting. */
  failOnParseError?: boolean
  /** Optional cancellation handle. */
  signal?: unknown
  /** Wall-clock timeout for the worker task in milliseconds. */
  timeoutMs?: number
}

/** Summary of an ast-grep rewrite pass, including whether disk writes occurred. */
export interface AstReplaceResult {
  /** Individual replacement records (may be large). */
  changes: Array<AstReplaceChange>
  /** Replacement counts grouped by file. */
  fileChanges: Array<AstReplaceFileChange>
  /** Total replacements applied or previewed. */
  totalReplacements: number
  /** Files that had at least one replacement. */
  filesTouched: number
  /** Files considered for rewriting. */
  filesSearched: number
  /** False when `dryRun` prevented writing. */
  applied: boolean
  /** True when limits stopped further replacements. */
  limitReached: boolean
  /** Parse or pattern errors when not failing the whole operation. */
  parseErrors?: Array<string>
}

/** A context line (before or after a match). */
export interface ContextLine {
  /** 1-indexed line number in the source file. */
  lineNumber: number
  /** Raw line content (trimmed line ending). */
  line: string
}

/**
 * Count tokens in `input`.
 *
 * `input` may be a single string or an array of strings; an array returns
 * the sum across all elements (counted in parallel when the global rayon pool
 * is available). Always returns a single token total — use this for any
 * aggregate budget question without paying a per-element napi crossing.
 *
 * Measures user/model content, not wire-protocol tokens: BPE encodings
 * use ordinary encoding (no special-token handling) and the Claude
 * encodings count message content without the fixed per-message frame.
 * Defaults to `o200k_base`; pass a `Claude*` encoding for exact Claude
 * counts, or the matching family encoding for Qwen/DeepSeek/Kimi/GLM.
 */
export declare function countTokens(input: string | string[], encoding?: Encoding | undefined | null): number

/** One jsdiff change object: a run of added, removed, or common tokens. */
export interface DiffChange {
  /** Joined token text for this run (lines keep their `\n` terminators). */
  value: string
  /** Number of tokens in this run. */
  count: number
  /** True when this run exists only in the new text. */
  added: boolean
  /** True when this run exists only in the old text. */
  removed: boolean
}

/**
 * Diff `oldText.split("
")` against `newText.split("
")` with jsdiff
 * `diffArrays` semantics (exact code-unit equality, empty lines preserved),
 * returning only run lengths.
 *
 * Callers that map line numbers — like hashline recovery — need the counts,
 * not another copy of the text.
 */
export declare function diffLineRuns(oldText: string, newText: string): Array<DiffRun>

/**
 * Line diff with jsdiff `diffLines(oldText, newText)` semantics (default
 * options). Change values keep line terminators, and common runs are joined
 * from the new text.
 */
export declare function diffLines(oldText: string, newText: string): Array<DiffChange>

/** A change run without its token text, for callers that only need counts. */
export interface DiffRun {
  /** Number of tokens in this run. */
  count: number
  /** True when this run exists only in the new text. */
  added: boolean
  /** True when this run exists only in the old text. */
  removed: boolean
}

/** One side of a streamed line diff. */
export declare const enum DiffSide {
  /** Original/base text. */
  Old = 'Old',
  /** Updated/target text. */
  New = 'New',
}

/** Observable ingestion state for [`DiffStream`]. */
export interface DiffStreamProgress {
  /** Complete old-side lines available for rendering. */
  oldLines: number
  /** Complete new-side lines available for rendering. */
  newLines: number
  /** Leading complete lines proven equal on both sides. */
  stableCommonLines: number
  /** Whether old-side ingestion has finished. */
  oldDone: boolean
  /** Whether new-side ingestion has finished. */
  newDone: boolean
  /** Whether either side contains a NUL byte/code unit. */
  binary: boolean
  /** Whether either native file exceeded its caller-provided size limit. */
  tooLarge: boolean
}

/** Exact line-diff output produced when a [`DiffStream`] finishes. */
export interface DiffStreamResult {
  /** Line-token Myers runs used to align the complete files. */
  runs: Array<DiffRun>
  /** Unified hunks for the requested context. */
  hunks: Array<PatchHunk>
  /** Whether the old text ends in a newline. */
  oldEndsNewline: boolean
  /** Whether the new text ends in a newline. */
  newEndsNewline: boolean
}

/**
 * Word diff with jsdiff `diffWords(oldText, newText)` semantics (default
 * options).
 *
 * Tokens carry surrounding whitespace, equality ignores it, and the
 * post-pass dedupes whitespace across change boundaries.
 */
export declare function diffWords(oldText: string, newText: string): Array<DiffChange>

/**
 * Whole-call apply outcome. `is_error` carries the model-facing failure in
 * `text` with no files.
 */
export interface EditApplyOutcome {
  text: string
  files: Array<EditFileOutcome>
  isError: boolean
}

/** Apply-time knobs. */
export interface EditApplyRequest {
  lspBatchId?: string
  lspFlush: boolean
}

/**
 * Auto-generated-file guard: the rejection message when `absolutePath`
 * (displayed as `displayPath`) must not be edited, else null. Missing or
 * unreadable files are editable.
 */
export declare function editAutoGeneratedMessage(absolutePath: string, displayPath: string): string | null

/** Tool description markdown for `mode`. */
export declare function editDescription(mode: string): string

/** Numbered unified diff plus the first changed line. */
export interface EditDiffResult {
  diff: string
  firstChangedLine?: number
}

/** Numbered unified diff between two texts (`generateDiffString`). */
export declare function editDiffString(oldText: string, newText: string, path?: string | undefined | null): EditDiffResult

/** A destructive file operation a payload declares. */
export interface EditFileOpIntent {
  /** `delete` | `move`. */
  kind: string
  path: string
  to?: string
}

/** One file's apply outcome. */
export interface EditFileOutcome {
  /** Absolute path. */
  path: string
  displayPath: string
  /** `create` | `update` | `delete`. */
  op: string
  moveTo?: string
  diff: string
  firstChangedLine?: number
  oldText?: string
  newText?: string
  snapshotsPruned: boolean
  diagnosticsJson?: string
  /** Engine warnings (already rendered into `text`). */
  warnings: Array<string>
  /** Model-facing text for this file. */
  text: string
  /** The file parsed before the edit and no longer does. */
  parseRegressed: boolean
}

/** One file's streamed diff preview. */
export interface EditFilePreview {
  /** Display path as authored (after suffix recovery). */
  path: string
  /** Numbered unified diff; mutually exclusive with `error`. */
  diff?: string
  firstChangedLine?: number
  /** Model-facing error text. */
  error?: string
  /** `create` | `update` | `delete`. */
  op?: string
  rename?: string
}

/** Lark grammar for `mode`, when it has a custom wire format. */
export declare function editGrammar(mode: string): string | null

/**
 * Inspect `argsJson` (the JSON-serialized, possibly partial tool args)
 * without touching the filesystem.
 */
export declare function editInspect(mode: string, argsJson: string): EditInspection

/**
 * Static projection of a payload: target paths, per-file digests, and
 * delete/move intents.
 */
export interface EditInspection {
  paths: Array<string>
  entries: Array<EditMatcherEntry>
  fileOps: Array<EditFileOpIntent>
}

/** `(path, added-lines digest)` for stream matchers. */
export interface EditMatcherEntry {
  path: string
  digest: string
}

/** Session-wide policy; TypeScript builds it once per tool call. */
export interface EditPolicy {
  cwd: string
  /** `replace` | `patch` | `apply_patch` | `hashline` | `sloppy`. */
  mode: string
  allowFuzzy: boolean
  fuzzyThreshold: number
  enforceSeenLines: boolean
  blockAutoGenerated: boolean
  planActive: boolean
  /** Root of the `local://` artifact sandbox; null when the session has none. */
  localSandboxRoot?: string
  /** Cached vault roots; null when the vault protocol is disabled. */
  vaultRoots?: Array<EditVaultRoot>
  homeDir: string
  /** The payload is a verbatim custom-format string, not JSON. */
  rawInput: boolean
}

/** A batch of previews for one session generation. */
export interface EditPreviewBatch {
  /** Monotonically increasing per session. */
  generation: number
  /** False for the final untrimmed pass after `finish()`. */
  streaming: boolean
  files: Array<EditFilePreview>
}

/** A cached `vault://` root. */
export interface EditVaultRoot {
  /** Vault name; `_` is the active vault. */
  name: string
  root: string
}

/** Host write request; the host owns the bytes. */
export interface EditWriteRequest {
  /** Absolute path. */
  path: string
  displayPath: string
  /** `create` | `update` | `delete` | `move`. */
  op: string
  /** Absolute destination for `move` (write `content` there, delete `path`). */
  moveTo?: string
  /** Final bytes as text; null for `delete`. */
  content?: string
  /** Last write of this call and the LSP batch requested a flush. */
  flushLsp: boolean
  lspBatchId?: string
}

/** Host write response. */
export interface EditWriteResponse {
  /** Text actually persisted (a bridge may reformat); empty for deletes. */
  written: string
  /** `FileDiagnosticsResult` serialized by the host; opaque here. */
  diagnosticsJson?: string
}

/** Tokenizer encoding to use. */
export declare const enum Encoding {
  /** GPT-4o / o1 / GPT-5 (default). */
  O200kBase = 'O200kBase',
  /** GPT-3.5 / GPT-4 / older. */
  Cl100kBase = 'Cl100kBase',
  /** Claude 3 … Opus 4.6 (ctok v3 reconstruction). */
  ClaudeV3 = 'ClaudeV3',
  /** Claude Opus 4.7–4.9 (ctok v4.7 reconstruction). */
  ClaudeV47 = 'ClaudeV47',
  /** Claude Opus 5+ (ctok v5 reconstruction). */
  ClaudeV5 = 'ClaudeV5',
  /** Claude Sonnet/Fable 5+ (live-measured non-opus v5 frame). */
  ClaudeV5Sonnet = 'ClaudeV5Sonnet',
  /** Qwen 3.5 / 3.6 / 3.8 (248k vocabulary). */
  Qwen3 = 'Qwen3',
  /** `DeepSeek` V3 … V4 (identical base BPE). */
  DeepSeekV3 = 'DeepSeekV3',
  /** Kimi K2 … K3. */
  KimiK2 = 'KimiK2',
  /** GLM-5.x exact; GLM-4.x near-exact. */
  Glm5 = 'Glm5',
}

/** Locate `<SM:EDIT path="…">` payloads the model emitted as plain text. */
export declare function extractInlineSloppyRegions(text: string): Array<InlineSloppyRegion>

/** Resolved filesystem entry kind for glob filters and match metadata. */
export declare const enum FileType {
  /** Regular file. */
  File = 1,
  /** Directory. */
  Dir = 2,
  /** Symbolic link. */
  Symlink = 3,
}

/** Fuzzy file path search for autocomplete. */
export declare function fuzzyFind(options: FuzzyFindOptions): Promise<FuzzyFindResult>

/** A single match in fuzzy find results. */
export interface FuzzyFindMatch {
  /** Relative path from the search root (uses `/` separators). */
  path: string
  /** Whether this entry is a directory. */
  isDirectory: boolean
  /** Match quality score (higher is better). */
  score: number
}

/** Options for fuzzy file path search. */
export interface FuzzyFindOptions {
  /** Fuzzy query to match against file paths (case-insensitive). */
  query: string
  /** Directory to search. */
  path: string
  /** Include hidden files (default: false). */
  hidden?: boolean
  /** Respect .gitignore (default: true). */
  gitignore?: boolean
  /** Enable walker scan caching (default: false). */
  cache?: boolean
  /** Maximum number of matches to return (default: 100). */
  maxResults?: number
  /** Abort signal for cancelling the operation. */
  signal?: unknown
  /** Timeout in milliseconds for the operation. */
  timeoutMs?: number
}

/** Result of fuzzy file path search. */
export interface FuzzyFindResult {
  /** Matched entries (up to `maxResults`). */
  matches: Array<FuzzyFindMatch>
  /** Total number of matches found (may exceed `matches.len()`). */
  totalMatches: number
}

/**
 * Get work profile data from the last N seconds.
 *
 * Always-on profiling - no need to start/stop. Just call this to get
 * recent activity.
 */
export declare function getWorkProfile(lastSeconds: number): WorkProfile

/**
 * Find filesystem entries matching a glob pattern.
 *
 * Resolves the search root, scans entries, applies glob and optional file-type
 * filters, and optionally streams each accepted match through `on_match`.
 *
 * When `sortByMtime` is enabled, the walker ranks matches by mtime before the
 * native layer applies final symlink-aware file-type filtering and callback
 * emission.
 *
 * # Errors
 * Returns an error when the search path cannot be resolved, the path is not a
 * directory, the glob pattern is invalid, or cancellation/timeout is
 * triggered.
 */
export declare function glob(options: GlobOptions, onMatch?: ((error: Error | null, match: GlobMatch) => void) | undefined | null): Promise<GlobResult>

/** A single filesystem entry from a directory scan. */
export interface GlobMatch {
  /** Relative path from the search root, using forward slashes. */
  path: string
  /** Resolved filesystem type for the match. */
  fileType: FileType
  /** Modification time in milliseconds since Unix epoch. */
  mtime?: number
  /** File size in bytes for regular files. */
  size?: number
}

/** Input options for `glob`, including traversal, filtering, and cancellation. */
export interface GlobOptions {
  /** Glob pattern to match (e.g., "*.ts"). */
  pattern: string
  /** Directory to search. */
  path: string
  /**
   * Filter by file type: "file", "dir", or "symlink". Symlinks are
   * matched for file/dir filters based on their target type.
   */
  fileType?: FileType
  /** Match simple patterns recursively by default (`*.ts` -> recursive). */
  recursive?: boolean
  /** Include hidden files (default: false). */
  hidden?: boolean
  /** Maximum number of results to return. */
  maxResults?: number
  /** Respect .gitignore files (default: true). */
  gitignore?: boolean
  /** Enable walker scan caching (default: false). */
  cache?: boolean
  /** Sort results by mtime (most recent first) before applying limit. */
  sortByMtime?: boolean
  /**
   * Include `node_modules` entries when the pattern does not explicitly
   * mention them.
   */
  includeNodeModules?: boolean
  /** Abort signal for cancelling the operation. */
  signal?: unknown
  /** Timeout in milliseconds for the operation. */
  timeoutMs?: number
}

/** Result payload returned by a glob operation. */
export interface GlobResult {
  /** Matched filesystem entries. */
  matches: Array<GlobMatch>
  /** Number of returned matches (`matches.len()`), clamped to `u32::MAX`. */
  totalMatches: number
}

/**
 * Search files for a regex pattern.
 *
 * # Arguments
 * - `options`: Pattern, path, filters, and output mode.
 * - `on_match`: Optional callback invoked per match/result.
 *
 * # Returns
 * Aggregated results across matching files.
 */
export declare function grep(options: GrepOptions, onMatch?: ((error: Error | null, match: GrepMatch) => void) | undefined | null): Promise<GrepResult>

/** A single match in a grep result. */
export interface GrepMatch {
  /** File path for the match (relative for directory searches). */
  path: string
  /** 1-indexed line number (0 for count-only entries). */
  lineNumber: number
  /** The matched line content (empty for count-only entries). */
  line: string
  /** Context lines before the match. */
  contextBefore?: Array<ContextLine>
  /** Context lines after the match. */
  contextAfter?: Array<ContextLine>
  /** Whether the line was truncated. */
  truncated?: boolean
  /** Per-file match count (count mode only). */
  matchCount?: number
}

/** Options for searching files on disk. */
export interface GrepOptions {
  /** Regex pattern to search for. */
  pattern: string
  /** Directory or file to search. */
  path: string
  /** Glob filter for filenames (e.g., "*.ts"). */
  glob?: string
  /** Filter by file type (e.g., "js", "py", "rust"). */
  type?: string
  /** Case-insensitive search. */
  ignoreCase?: boolean
  /** Enable multiline matching. */
  multiline?: boolean
  /** Include hidden files (default: true). */
  hidden?: boolean
  /** Respect .gitignore files (default: true). */
  gitignore?: boolean
  /** Maximum number of matches to return. */
  maxCount?: number
  /** Skip first N matches. */
  offset?: number
  /** Lines of context before matches. */
  contextBefore?: number
  /** Lines of context after matches. */
  contextAfter?: number
  /** Lines of context before/after matches (legacy). */
  context?: number
  /** Truncate lines longer than this (characters). */
  maxColumns?: number
  /** Output mode (content, filesWithMatches, or count). */
  mode?: GrepOutputMode
  /**
   * Maximum matches collected per file (content mode). Keeps one hot file
   * from exhausting the global `max_count` budget before other files are
   * reached.
   */
  maxCountPerFile?: number
  /** Abort signal for cancelling the operation. */
  signal?: unknown
  /** Timeout in milliseconds for the operation. */
  timeoutMs?: number
}

/** Output mode for [`search`] and [`grep`] (string values match JS callers). */
export declare const enum GrepOutputMode {
  /** Emit matched lines (and optional context lines). */
  Content = 'content',
  /** Emit per-file or total counts instead of line content. */
  Count = 'count',
  /** Emit one row per file that matched, without line content. */
  FilesWithMatches = 'filesWithMatches',
}

/** Result of searching files. */
export interface GrepResult {
  /** Matches or per-file counts, depending on output mode. */
  matches: Array<GrepMatch>
  /**
   * Total matches across all files, or matched file count in filesWithMatches
   * mode.
   */
  totalMatches: number
  /** Number of files with at least one match. */
  filesWithMatches: number
  /** Number of files searched. */
  filesSearched: number
  /** Whether the limit/offset stopped the search early. */
  limitReached?: boolean
  /** Number of files skipped because they exceed the size limit. */
  skippedOversized?: number
}

/**
 * Count canonical hashline op header shapes (`PUT N.=M:`, `CUT N*`, …) in
 * a payload; empty when it carries no hashline ops.
 */
export declare function hashlineCountOps(input: string): Array<HashlineOpCount>

/** 4-hex hashline content tag for `text`. */
export declare function hashlineFileHash(text: string): string

/** `[path#TAG]` section header. */
export declare function hashlineFormatHeader(path: string, tag: string): string

/** `N:line` numbered display rows starting at `startLine` (default 1). */
export declare function hashlineFormatNumberedLines(text: string, startLine?: number | undefined | null): string

/** Count of one canonical hashline op header shape in a payload. */
export interface HashlineOpCount {
  label: string
  count: number
}

/** Strip hashline display prefixes (`N:` / `+N:` …) from pasted rows. */
export declare function hashlineStripPrefixes(lines: Array<string>): Array<string>

/**
 * Quick check if content matches a pattern.
 *
 * # Arguments
 * - `content`: `Uint8Array`/`Buffer` (zero-copy) or `string` (UTF-8).
 * - `pattern`: `Uint8Array`/`Buffer` (zero-copy) or `string` (UTF-8).
 * - `ignore_case`: Case-insensitive matching.
 * - `multiline`: Enable multiline regex mode.
 *
 * # Returns
 * True if any match exists; false on no match.
 */
export declare function hasMatch(content: string | Uint8Array, pattern: string | Uint8Array, ignoreCase?: boolean | undefined | null, multiline?: boolean | undefined | null): boolean

/** One stray sloppy payload region inside prose (UTF-16 offsets). */
export interface InlineSloppyRegion {
  start: number
  end: number
  payload: string
}

/**
 * Invalidate the walker scan cache.
 *
 * When called with a path, removes entries for roots containing that path.
 * When called without a path, clears the entire cache.
 *
 * Intended to be called after agent file mutations: write, edit, rename, or
 * delete.
 */
export declare function invalidateFsScanCache(path?: string | undefined | null): void

/** A single match in the content. */
export interface Match {
  /** 1-indexed line number. */
  lineNumber: number
  /** The matched line content. */
  line: string
  /** Context lines before the match. */
  contextBefore?: Array<ContextLine>
  /** Context lines after the match. */
  contextAfter?: Array<ContextLine>
  /** Whether the line was truncated. */
  truncated?: boolean
}

/** Decode notebook JSON into the editable cell-marker text. */
export declare function notebookToEditableText(json: string, displayPath: string): string

/** One hunk of a unified diff, matching jsdiff `structuredPatch` hunks. */
export interface PatchHunk {
  /** 1-based first line of the hunk in the old text. */
  oldStart: number
  /** Number of old-text lines covered by the hunk. */
  oldLines: number
  /** 1-based first line of the hunk in the new text. */
  newStart: number
  /** Number of new-text lines covered by the hunk. */
  newLines: number
  /**
   * Hunk body: `+`/`-`/` `-prefixed lines without trailing newlines, plus
   * `\ No newline at end of file` markers where applicable.
   */
  lines: Array<string>
}

/**
 * Render one snapcompact frame on a libuv worker: print pre-normalized text
 * onto a `size`-wide bitmap and encode it as PNG.
 *
 * The bitmap height hugs the rows the text actually occupies
 * (`usedRows * lineRepeat * cellHeight`), so a partially filled frame never
 * pays for blank padding rows. The glyph grid holds `floor(size/cellWidth) *
 * floor(size/cellHeight/lineRepeat)` characters; input beyond that is ignored.
 * Native-cell bitmap-font shapes encode as indexed PNG; stretched bitmap-font
 * shapes (target cell != font cell) encode as RGB. TrueType shapes encode RGB
 * directly from grayscale coverage.
 * `stretch: false` pins bitmap fonts to the indexed path, printing
 * natural-size glyphs on the requested cell box; `columns: 2` flows
 * pre-wrapped newline-separated lines down two newspaper columns.
 * `U+000E`/`U+000F` in `text` toggle dim-gray ink spans without occupying a
 * cell.
 * Returns a promise for the PNG encoded as base64, created as a one-byte
 * (Latin-1) JS string straight from native code — no `Uint8Array` hop or
 * JS-side re-encode.
 */
export declare function renderSnapcompactPng(text: string, options: SnapcompactRenderOptions): Promise<string>

/**
 * Search content for a pattern (one-shot, compiles pattern each time).
 * For repeated searches with the same pattern, use [`grep`] with file filters.
 *
 * # Arguments
 * - `content`: `Uint8Array`/`Buffer` (zero-copy) or `string` (UTF-8).
 * - `options`: Regex settings, context, and output mode.
 *
 * # Returns
 * Match list plus counts/limit status; errors are surfaced in `error`.
 */
export declare function search(content: string | Uint8Array, options: SearchOptions): SearchResult

/** Options for searching file content. */
export interface SearchOptions {
  /** Regex pattern to search for. */
  pattern: string
  /** Case-insensitive search. */
  ignoreCase?: boolean
  /** Enable multiline matching. */
  multiline?: boolean
  /** Maximum number of matches to return. */
  maxCount?: number
  /** Skip first N matches. */
  offset?: number
  /** Lines of context before matches. */
  contextBefore?: number
  /** Lines of context after matches. */
  contextAfter?: number
  /** Lines of context before/after matches (legacy). */
  context?: number
  /** Truncate lines longer than this (characters). */
  maxColumns?: number
  /** Output mode (content or count). */
  mode?: GrepOutputMode
}

/** Result of searching content. */
export interface SearchResult {
  /** All matches found. */
  matches: Array<Match>
  /** Total number of matches (may exceed `matches.len()` due to offset/limit). */
  matchCount: number
  /** Whether the limit was reached. */
  limitReached: boolean
  /** Error message, if any. */
  error?: string
}

/** Shape options for one snapcompact frame. */
export interface SnapcompactRenderOptions {
  /**
   * Frame width in pixels; also bounds the grid rows
   * (`floor(size/cellHeight/lineRepeat)`). Output height hugs the rows the
   * text actually uses instead of padding to a square.
   */
  size: number
  /**
   * Bundled font: `"5x8"`, `"6x12"`, `"8x13"` (X.org BDF), `"8x8"`
   * (unscii-8), or `"silver"` (embedded TrueType). Default `"5x8"`.
   */
  font?: string
  /**
   * Target cell advance in pixels. Differing from the font's natural cell
   * triggers the Lanczos stretch path. Default: font natural width.
   */
  cellWidth?: number
  /** Target cell pitch in pixels. Default: font natural height. */
  cellHeight?: number
  /**
   * Ink variant: `"sent"` (six-hue sentence cycling) or `"bw"` (black).
   * Default `"sent"`.
   */
  variant?: string
  /**
   * Print each text line this many times; copies after the first sit on a
   * pale highlight band. Default 1.
   */
  lineRepeat?: number
  /**
   * Stretch behavior. Unset: auto — Lanczos-stretch whenever the target
   * cell differs from the font's natural cell. `false`: never stretch —
   * render indexed with glyphs at natural size on the requested cell box
   * (e.g. 8x13 glyphs on an 8x16 pitch, the "8on16" shapes). `true`: force
   * the stretch path (identical to auto; natural cells render indexed).
   */
  stretch?: boolean
  /**
   * Layout columns: `1` (default) row-major grid; `2` two newspaper "doc"
   * columns of pre-wrapped newline-separated lines.
   */
  columns?: number
}

/**
 * Return the subset of `chars` that the named snapcompact font can render.
 *
 * The TypeScript normalizer uses this to keep Unicode text intact only when
 * the selected native font has a glyph for it; renderer control codes are
 * considered renderable because they are interpreted outside font lookup.
 */
export declare function snapcompactSupportedChars(font: string, chars: string): string

/**
 * Unified-diff hunks with jsdiff
 * `structuredPatch(_, _, oldText, newText, _, _, { context }).hunks`
 * semantics. `context` defaults to 4 like jsdiff.
 */
export declare function structuredPatchHunks(oldText: string, newText: string, context?: number | undefined | null): Array<PatchHunk>

/** Profiling results returned to JavaScript. */
export interface WorkProfile {
  /** Folded stack format for flamegraph tools. */
  folded: string
  /** Markdown summary of profiling results. */
  summary: string
  /** SVG flamegraph (if generation succeeded). */
  svg?: string
  /** Total profiled duration in milliseconds. */
  totalMs: number
  /** Number of samples collected. */
  sampleCount: number
}
