/* auto-generated by NAPI-RS */
/* eslint-disable */

/** One edit tool call's streaming session. */
export declare class EditSession {
  /**
   * Open a session. `onPreview` (optional) receives every settled preview
   * batch; batches are delivered one at a time, in generation order.
   */
  constructor(store: EditStore, policy: EditPolicy, onPreview?: ((error: Error | null, batch: EditPreviewBatch) => void) | undefined | null)
  /** Append a raw streamed argument fragment. */
  push(delta: string): void
  /** Replace the buffer with the complete argument JSON (no-delta path). */
  setArgsJson(argsJson: string): void
  /** Arguments are complete; triggers the final untrimmed preview. */
  finish(): void
  /**
   * Stage and apply the finished edit through `writer`. Never rejects for
   * engine failures: those come back as `isError` outcomes carrying the
   * model-facing message.
   */
  apply(request: EditApplyRequest, writer: (error: Error | null, request: EditWriteRequest) => Promise<EditWriteResponse>): Promise<EditApplyOutcome>
  /** Stop the preview pump and release buffers. */
  close(): void
}

/** Session-scoped snapshots, clipboard registers, and the no-op loop guard. */
export declare class EditStore {
  constructor()
  /**
   * Record `text` (any line endings) as the current snapshot of
   * `absolutePath` and return its 4-hex tag.
   */
  recordSnapshot(absolutePath: string, text: string, seenLines?: Array<number> | undefined | null): string
  /**
   * Read `absolutePath` from disk and record it; null when the file is
   * unreadable or larger than 4 MiB.
   */
  recordSnapshotFile(absolutePath: string, seenLines?: Array<number> | undefined | null): string | null
  /** Merge displayed lines into the snapshot tagged `tag`. */
  recordSeenLines(absolutePath: string, tag: string, lines: Array<number>): void
  /**
   * Merge the lines a hashline-formatted `body` displays into the
   * snapshot tagged `tag`.
   */
  recordSeenLinesFromBody(absolutePath: string, tag: string, body: string): void
  /** Latest recorded text for `absolutePath`. */
  headText(absolutePath: string): string | null
  /** Latest recorded tag for `absolutePath`. */
  headHash(absolutePath: string): string | null
  /** Recorded text of `absolutePath` tagged `hash`. */
  byHashText(absolutePath: string, hash: string): string | null
  /**
   * Displayed lines recorded for the snapshot tagged `hash`; null when no
   * provenance was recorded.
   */
  seenLines(absolutePath: string, hash: string): Array<number> | null
  invalidate(absolutePath: string): void
  relocate(from: string, to: string): void
  clear(): void
}

/**
 * Apply ast-grep rewrite rules to matching files; honors `dryRun` and returns
 * a promise.
 */
export declare function astEdit(options: AstReplaceOptions): Promise<AstReplaceResult>

/** One ast-grep match with source range and optional meta-variables. */
export interface AstFindMatch {
  /** Display path of the matching file. */
  path: string
  /** Matched source text. */
  text: string
  /** Start byte offset in the file (UTF-8 byte index). */
  byteStart: number
  /** End byte offset in the file (exclusive UTF-8 byte index). */
  byteEnd: number
  /** 1-based start line. */
  startLine: number
  /** 1-based start column. */
  startColumn: number
  /** 1-based end line. */
  endLine: number
  /** 1-based end column. */
  endColumn: number
  /** Meta-variable name to captured text, when `includeMeta` was enabled. */
  metaVariables?: Record<string, string>
}

/** Options for `astGrep`: patterns, scan scope, and match limits. */
export interface AstFindOptions {
  /** ast-grep patterns to search for (OR across patterns). */
  patterns?: Array<string>
  /** Language override; otherwise inferred from file extension per candidate. */
  lang?: string
  /** Single file or directory to scan (combined with `glob` when set). */
  path?: string
  /** Optional glob filter relative to the search root. */
  glob?: string
  /** Rule selector for multi-rule ast-grep configurations. */
  selector?: string
  /** Pattern strictness; defaults to smart matching when omitted. */
  strictness?: AstMatchStrictness
  /** Maximum matches to return after `offset` (default applies when omitted). */
  limit?: number
  /** Number of leading matches to skip before applying `limit`. */
  offset?: number
  /** When true, include meta-variable bindings per match. */
  includeMeta?: boolean
  /**
   * Reserved for contextual snippets; not used by the current native find
   * path.
   */
  context?: number
  /** Optional cancellation handle (library-specific). */
  signal?: unknown
  /** Wall-clock timeout for the worker task in milliseconds. */
  timeoutMs?: number
}

/** Aggregated search statistics and any parse or compile diagnostics. */
export interface AstFindResult {
  /** Page of matches after sort, offset, and limit. */
  matches: Array<AstFindMatch>
  /** Total matches found before paging (can exceed `matches.length`). */
  totalMatches: number
  /** Distinct files that contained at least one match. */
  filesWithMatches: number
  /** Files examined for the query. */
  filesSearched: number
  /** True when results were truncated by `limit`. */
  limitReached: boolean
  /** Non-fatal parse or pattern errors collected during the run. */
  parseErrors?: Array<string>
}

/**
 * Search source files with ast-grep patterns; returns a promise resolved on a
 * worker thread.
 */
export declare function astGrep(options: AstFindOptions): Promise<AstFindResult>

/**
 * Match ast-grep patterns against an in-memory source string; returns a
 * promise resolved on a worker thread.
 *
 * This is the file-free counterpart to [`ast_grep`]: callers that already hold
 * the source (streaming buffers, generated code, editor contents) avoid a
 * temp-file round trip. `lang` is required since there is no path to infer it
 * from.
 */
export declare function astMatch(options: AstMatchOptions): Promise<AstMatchResult>

/**
 * Options for `astMatch`: run ast-grep patterns against an in-memory source
 * string instead of files on disk.
 */
export interface AstMatchOptions {
  /** Source code to match against (parsed in memory, never read from disk). */
  source: string
  /** Language of `source` (required; e.g. "ts", "tsx", "rust", "python"). */
  lang: string
  /** ast-grep patterns to search for (OR across patterns). */
  patterns: Array<string>
  /** Rule selector for multi-rule ast-grep configurations. */
  selector?: string
  /** Pattern strictness; defaults to smart matching when omitted. */
  strictness?: AstMatchStrictness
  /** Maximum matches to return after `offset` (default applies when omitted). */
  limit?: number
  /** Number of leading matches to skip before applying `limit`. */
  offset?: number
  /** When true, include meta-variable bindings per match. */
  includeMeta?: boolean
  /** Optional cancellation handle (library-specific). */
  signal?: unknown
  /** Wall-clock timeout for the worker task in milliseconds. */
  timeoutMs?: number
}

/** Result of an in-memory `astMatch` run. */
export interface AstMatchResult {
  /** Page of matches after sort, offset, and limit. */
  matches: Array<AstFindMatch>
  /** Total matches found before paging (can exceed `matches.length`). */
  totalMatches: number
  /** True when results were truncated by `limit`. */
  limitReached: boolean
  /** Non-fatal parse or pattern-compile errors collected during the run. */
  parseErrors?: Array<string>
}

/** ast-grep pattern strictness (controls how patterns match syntax). */
export declare const enum AstMatchStrictness {
  /** Match at the concrete syntax tree level. */
  Cst = 'cst',
  /** Balanced default suitable for most searches. */
  Smart = 'smart',
  /** Match at the AST level. */
  Ast = 'ast',
  /** More permissive matching. */
  Relaxed = 'relaxed',
  /** Match structural signatures. */
  Signature = 'signature',
  /** Template-style pattern matching. */
  Template = 'template',
}

/**
 * One textual replacement applied to a file (before/after slice and
 * coordinates).
 */
export interface AstReplaceChange {
  /** File path for this change. */
  path: string
  /** Original matched text. */
  before: string
  /** Replacement text. */
  after: string
  /** Start byte offset of the replaced span. */
  byteStart: number
  /** End byte offset of the replaced span (exclusive). */
  byteEnd: number
  /**
   * Length of deleted text in bytes (may differ from `byteEnd - byteStart`
   * for edge cases).
   */
  deletedLength: number
  /** 1-based start line of the match. */
  startLine: number
  /** 1-based start column. */
  startColumn: number
  /** 1-based end line. */
  endLine: number
  /** 1-based end column. */
  endColumn: number
}

/** Per-file replacement count after an `astEdit` run. */
export interface AstReplaceFileChange {
  /** File that had replacements. */
  path: string
  /** Number of replacements in that file. */
  count: number
}

/**
 * Options for `astEdit`: rewrite rules, scan scope, safety limits, and
 * dry-run.
 */
export interface AstReplaceOptions {
  /** Map of pattern string to replacement template. */
  rewrites?: Record<string, string>
  /**
   * Language override applied to every file; otherwise inferred per file, so
   * mixed-language paths rewrite each file in its own language.
   */
  lang?: string
  /** Single file or directory to rewrite. */
  path?: string
  /** Optional glob filter within the search root. */
  glob?: string
  /** Rule selector for multi-rule configurations. */
  selector?: string
  /** Pattern strictness for rewrites. */
  strictness?: AstMatchStrictness
  /** When true (default), compute changes without writing files. */
  dryRun?: boolean
  /** Cap on replacement applications across all files. */
  maxReplacements?: number
  /** Cap on distinct files that may be modified. */
  maxFiles?: number
  /** Fail the operation when a file cannot be parsed for rewriting. */
  failOnParseError?: boolean
  /** Optional cancellation handle. */
  signal?: unknown
  /** Wall-clock timeout for the worker task in milliseconds. */
  timeoutMs?: number
}

/** Summary of an ast-grep rewrite pass, including whether disk writes occurred. */
export interface AstReplaceResult {
  /** Individual replacement records (may be large). */
  changes: Array<AstReplaceChange>
  /** Replacement counts grouped by file. */
  fileChanges: Array<AstReplaceFileChange>
  /** Total replacements applied or previewed. */
  totalReplacements: number
  /** Files that had at least one replacement. */
  filesTouched: number
  /** Files considered for rewriting. */
  filesSearched: number
  /** False when `dryRun` prevented writing. */
  applied: boolean
  /** True when limits stopped further replacements. */
  limitReached: boolean
  /** Parse or pattern errors when not failing the whole operation. */
  parseErrors?: Array<string>
}

/**
 * Whole-call apply outcome. `is_error` carries the model-facing failure in
 * `text` with no files.
 */
export interface EditApplyOutcome {
  text: string
  files: Array<EditFileOutcome>
  isError: boolean
}

/** Apply-time knobs. */
export interface EditApplyRequest {
  lspBatchId?: string
  lspFlush: boolean
}

/**
 * Auto-generated-file guard: the rejection message when `absolutePath`
 * (displayed as `displayPath`) must not be edited, else null. Missing or
 * unreadable files are editable.
 */
export declare function editAutoGeneratedMessage(absolutePath: string, displayPath: string): string | null

/** Tool description markdown for `mode`. */
export declare function editDescription(mode: string): string

/** Numbered unified diff plus the first changed line. */
export interface EditDiffResult {
  diff: string
  firstChangedLine?: number
}

/** Numbered unified diff between two texts (`generateDiffString`). */
export declare function editDiffString(oldText: string, newText: string, path?: string | undefined | null): EditDiffResult

/** A destructive file operation a payload declares. */
export interface EditFileOpIntent {
  /** `delete` | `move`. */
  kind: string
  path: string
  to?: string
}

/** One file's apply outcome. */
export interface EditFileOutcome {
  /** Absolute path. */
  path: string
  displayPath: string
  /** `create` | `update` | `delete`. */
  op: string
  moveTo?: string
  diff: string
  firstChangedLine?: number
  oldText?: string
  newText?: string
  snapshotsPruned: boolean
  diagnosticsJson?: string
  /** Engine warnings (already rendered into `text`). */
  warnings: Array<string>
  /** Model-facing text for this file. */
  text: string
  /** The file parsed before the edit and no longer does. */
  parseRegressed: boolean
}

/** One file's streamed diff preview. */
export interface EditFilePreview {
  /** Display path as authored (after suffix recovery). */
  path: string
  /** Numbered unified diff; mutually exclusive with `error`. */
  diff?: string
  firstChangedLine?: number
  /** Model-facing error text. */
  error?: string
  /** `create` | `update` | `delete`. */
  op?: string
  rename?: string
}

/** Lark grammar for `mode`, when it has a custom wire format. */
export declare function editGrammar(mode: string): string | null

/**
 * Inspect `argsJson` (the JSON-serialized, possibly partial tool args)
 * without touching the filesystem.
 */
export declare function editInspect(mode: string, argsJson: string): EditInspection

/**
 * Static projection of a payload: target paths, per-file digests, and
 * delete/move intents.
 */
export interface EditInspection {
  paths: Array<string>
  entries: Array<EditMatcherEntry>
  fileOps: Array<EditFileOpIntent>
}

/** `(path, added-lines digest)` for stream matchers. */
export interface EditMatcherEntry {
  path: string
  digest: string
}

/** Session-wide policy; TypeScript builds it once per tool call. */
export interface EditPolicy {
  cwd: string
  /** `replace` | `patch` | `apply_patch` | `hashline` | `sloppy`. */
  mode: string
  allowFuzzy: boolean
  fuzzyThreshold: number
  enforceSeenLines: boolean
  blockAutoGenerated: boolean
  planActive: boolean
  /** Root of the `local://` artifact sandbox; null when the session has none. */
  localSandboxRoot?: string
  /** Cached vault roots; null when the vault protocol is disabled. */
  vaultRoots?: Array<EditVaultRoot>
  homeDir: string
  /** The payload is a verbatim custom-format string, not JSON. */
  rawInput: boolean
}

/** A batch of previews for one session generation. */
export interface EditPreviewBatch {
  /** Monotonically increasing per session. */
  generation: number
  /** False for the final untrimmed pass after `finish()`. */
  streaming: boolean
  files: Array<EditFilePreview>
}

/** A cached `vault://` root. */
export interface EditVaultRoot {
  /** Vault name; `_` is the active vault. */
  name: string
  root: string
}

/** Host write request; the host owns the bytes. */
export interface EditWriteRequest {
  /** Absolute path. */
  path: string
  displayPath: string
  /** `create` | `update` | `delete` | `move`. */
  op: string
  /** Absolute destination for `move` (write `content` there, delete `path`). */
  moveTo?: string
  /** Final bytes as text; null for `delete`. */
  content?: string
  /** Last write of this call and the LSP batch requested a flush. */
  flushLsp: boolean
  lspBatchId?: string
}

/** Host write response. */
export interface EditWriteResponse {
  /** Text actually persisted (a bridge may reformat); empty for deletes. */
  written: string
  /** `FileDiagnosticsResult` serialized by the host; opaque here. */
  diagnosticsJson?: string
}

/** Locate `<SM:EDIT path="…">` payloads the model emitted as plain text. */
export declare function extractInlineSloppyRegions(text: string): Array<InlineSloppyRegion>

/** Resolved filesystem entry kind for glob filters and match metadata. */
export declare const enum FileType {
  /** Regular file. */
  File = 1,
  /** Directory. */
  Dir = 2,
  /** Symbolic link. */
  Symlink = 3,
}

/**
 * Get work profile data from the last N seconds.
 *
 * Always-on profiling - no need to start/stop. Just call this to get
 * recent activity.
 */
export declare function getWorkProfile(lastSeconds: number): WorkProfile

/** A single filesystem entry from a directory scan. */
export interface GlobMatch {
  /** Relative path from the search root, using forward slashes. */
  path: string
  /** Resolved filesystem type for the match. */
  fileType: FileType
  /** Modification time in milliseconds since Unix epoch. */
  mtime?: number
  /** File size in bytes for regular files. */
  size?: number
}

/**
 * Count canonical hashline op header shapes (`PUT N.=M:`, `CUT N*`, …) in
 * a payload; empty when it carries no hashline ops.
 */
export declare function hashlineCountOps(input: string): Array<HashlineOpCount>

/** 4-hex hashline content tag for `text`. */
export declare function hashlineFileHash(text: string): string

/** `[path#TAG]` section header. */
export declare function hashlineFormatHeader(path: string, tag: string): string

/** `N:line` numbered display rows starting at `startLine` (default 1). */
export declare function hashlineFormatNumberedLines(text: string, startLine?: number | undefined | null): string

/** Count of one canonical hashline op header shape in a payload. */
export interface HashlineOpCount {
  label: string
  count: number
}

/** Strip hashline display prefixes (`N:` / `+N:` …) from pasted rows. */
export declare function hashlineStripPrefixes(lines: Array<string>): Array<string>

/** One stray sloppy payload region inside prose (UTF-16 offsets). */
export interface InlineSloppyRegion {
  start: number
  end: number
  payload: string
}

/**
 * Invalidate the walker scan cache.
 *
 * When called with a path, removes entries for roots containing that path.
 * When called without a path, clears the entire cache.
 *
 * Intended to be called after agent file mutations: write, edit, rename, or
 * delete.
 */
export declare function invalidateFsScanCache(path?: string | undefined | null): void

/** Decode notebook JSON into the editable cell-marker text. */
export declare function notebookToEditableText(json: string, displayPath: string): string

/** Profiling results returned to JavaScript. */
export interface WorkProfile {
  /** Folded stack format for flamegraph tools. */
  folded: string
  /** Markdown summary of profiling results. */
  summary: string
  /** SVG flamegraph (if generation succeeded). */
  svg?: string
  /** Total profiled duration in milliseconds. */
  totalMs: number
  /** Number of samples collected. */
  sampleCount: number
}
