// ── Canonical coding-agent → UI runtime events ─────────────────────────────────

export interface MemoryUpdateEvent {
	type: "memory_update";
	kind:
		| "observations_added"
		| "reflections_added"
		| "reflections_evolved"
		| "observations_dropped"
		| "cleared";
	count: number;
	items?: Array<{ id: string; content: string; relevance?: string }>;
}

export interface TokenEvent {
	type: "token";
	token: string;
}

export interface ThinkingTokenEvent {
	type: "thinking_token";
	token: string;
}

export interface MessageUpdateEvent {
	type: "message_update";
	turnId: string;
	message: {
		role: string;
		content: string | null;
		tool_calls?: Array<{
			id: string;
			name: string;
			arguments: string;
		}>;
	};
}

/** Coherent mid-stream reasoning snapshot — the accumulated text so far, not a delta. */
export interface ReasoningUpdateEvent {
	type: "message_reasoning_update";
	turnId: string;
	reasoning: string;
}

export interface TurnStartEvent {
	type: "turn_start";
	turnId: string;
}

export interface TurnEndEvent {
	type: "turn_end";
	turnId: string;
	finalMessage?: MessageUpdateEvent["message"];
}

/** One provider/tool iteration inside the current user-visible agent run. */
export interface AgentIterationStartEvent {
	type: "agent_iteration_start";
	iteration: number;
}

export interface ToolCallStartEvent {
	type: "tool_call_start";
	toolName: string;
	args: Record<string, unknown>;
	toolCallId: string;
}

export interface ToolCallUpdateEvent {
	type: "tool_call_update";
	toolCallId: string;
	delta: string;
}

export interface ToolCallIdUpdateEvent {
	type: "tool_call_id_update";
	previousToolCallId: string;
	toolCallId: string;
}

export interface ToolStartEvent {
	type: "tool_execution_start";
	toolName: string;
	args: Record<string, unknown>;
	turnId?: string;
	toolCallId: string;
}

export interface ToolEndEvent {
	type: "tool_execution_end";
	toolName: string;
	result?: string;
	isError?: boolean;
	turnId?: string;
	toolCallId: string;
	// Structured metadata the tool returned alongside its text result.
	details?: Record<string, unknown>;
}

export interface ToolUpdateEvent {
	type: "tool_execution_update";
	toolName: string;
	partialResult: string;
	turnId?: string;
	toolCallId: string;
}

export interface PhaseEvent {
	type: "phase";
	state:
		| "ready"
		| "thinking"
		| "streaming"
		| "tool"
		| "verifying"
		| "permission"
		| "compacting"
		| "branching"
		| "retrying"
		| "cancelling"
		| "error";
	note?: string;
}

export interface ContextUpdateEvent {
	type: "context_update";
	tokens: number;
	maxTokens?: number;
	compacted?: boolean;
	/** null means the provider supplied no cache telemetry. */
	cachedTokens?: number | null;
	/** Tokens sent to the provider (prompt/input); null means unavailable. */
	promptTokens?: number | null;
	/** Tokens generated by the provider (completion/output); null means unavailable. */
	completionTokens?: number | null;
}

export interface CompactionEvent {
	type: "compaction";
	reason: string;
	tokensBefore?: number;
	tokensAfter?: number;
}

export interface RepairEvent {
	type: "repair_nudge";
	turnId?: string;
	repairStage?: string;
	attempt?: number;
	toolName?: string;
	errorType?: string;
	message?: string;
}

export interface TodosEvent {
	type: "todos";
	todos: Array<{
		id: number;
		subject: string;
		description?: string;
		activeForm?: string;
		status: "pending" | "in_progress" | "completed" | "deleted";
		blockedBy?: number[];
		owner?: string;
		metadata?: Record<string, unknown>;
	}>;
}

export interface SteeredEvent {
	type: "steered";
	message: string;
}

export interface QueueUpdateEvent {
	type: "queue_update";
	steering: string[];
	followUp: string[];
	nextTurn?: string[];
}

export interface ModelSelectEvent {
	type: "model_select";
	model: string;
}

// Retry / error observability
export interface AgentRetryStartEvent {
	type: "agent_retry_start";
	attempt: number;
	maxRetries: number;
	delayMs: number;
	error: string;
	reason?: "compaction" | "error" | "overflow" | "rate_limit";
}

export interface AgentRetryEndEvent {
	type: "agent_retry_end";
	attempt: number;
	success: boolean;
	reason?: "compaction" | "error" | "overflow" | "rate_limit";
}

export interface AgentErrorEvent {
	type: "agent_error";
	message: string;
	phase: "model" | "tool" | "compaction" | "network" | "other";
	recoverable: boolean;
}

export interface RuntimeStatusEvent {
	type: "runtime_status";
	runPhase: string;
	retry?: string;
	repair?: string;
	activeSubagents: number;
}

// A standalone status line (retry / error / model / stopped) rendered as its
// own iconed, coloured chunk rather than folded into assistant prose.
export interface NoticeEvent {
	type: "notice";
	level: "info" | "warn" | "error" | "success";
	label: string;
	text: string;
}

// One ordered chunk of a subagent's activity — thinking/response text or a
// tool call — carrying the child event's own emit-time sequence number so the
// transcript can interleave text and tool calls in true chronological order,
// the same way the parent agent's own AssistantChunk stream is interleaved.
export type SubagentChunkEvent =
	| {
			type: "subagent_chunk";
			agentId: string;
			seq: number;
			kind: "thinking" | "content";
			delta: string;
			taskIndex?: number;
	  }
	| {
			type: "subagent_chunk";
			agentId: string;
			seq: number;
			kind: "tool_execution_start";
			toolCallId: string;
			toolName: string;
			args: string;
			taskIndex?: number;
	  }
	| {
			type: "subagent_chunk";
			agentId: string;
			seq: number;
			kind: "tool_call_id_update";
			previousToolCallId: string;
			toolCallId: string;
			taskIndex?: number;
	  }
	| {
			type: "subagent_chunk";
			agentId: string;
			seq: number;
			kind: "tool_execution_end";
			toolCallId: string;
			toolName: string;
			result: string;
			isError: boolean;
			taskIndex?: number;
	  };

// Structured start/end lifecycle for one subagent run, carrying its taskIndex
// when spawned as part of a spawn_agents batch — the single source of truth
// for per-task status, replacing the old streamOutput marker-string protocol
// (`▶ N agent` / `✓ N agent` / `× N agent`).
export type SubagentLifecycleEvent =
	| {
			type: "subagent_lifecycle";
			phase: "start";
			agentId: string;
			agent: string;
			task: string;
			taskIndex?: number;
	  }
	| {
			type: "subagent_lifecycle";
			phase: "end";
			agentId: string;
			agent: string;
			result: string;
			isError: boolean;
			turns?: number;
			taskIndex?: number;
	  };

// A tool call is paused waiting for the user's allow/deny decision. The UI
// answers via bridge.respondToPermission(toolCallId, decision).
export interface PermissionRequestEvent {
	type: "permission_request";
	toolName: string;
	toolCallId: string;
	args: Record<string, unknown>;
}

export interface QuestionRequestEvent {
	type: "question_request";
	questionId: string;
	questions: Array<{
		id: string;
		header?: string;
		question: string;
		choices: Array<{ value: string; label: string; description?: string }>;
	}>;
}

export type RuntimeEvent =
	| TokenEvent
	| ThinkingTokenEvent
	| MessageUpdateEvent
	| ReasoningUpdateEvent
	| TurnStartEvent
	| TurnEndEvent
	| AgentIterationStartEvent
	| ToolCallStartEvent
	| ToolCallUpdateEvent
	| ToolCallIdUpdateEvent
	| ToolStartEvent
	| ToolUpdateEvent
	| ToolEndEvent
	| QueueUpdateEvent
	| PhaseEvent
	| ContextUpdateEvent
	| CompactionEvent
	| RepairEvent
	| TodosEvent
	| SteeredEvent
	| ModelSelectEvent
	| NoticeEvent
	| SubagentChunkEvent
	| SubagentLifecycleEvent
	| PermissionRequestEvent
	| QuestionRequestEvent
	| MemoryUpdateEvent
	| AgentRetryStartEvent
	| AgentRetryEndEvent
	| RuntimeStatusEvent
	| AgentErrorEvent;

/** Event names are derived from the canonical discriminated union so the two
 * cannot drift as new runtime events are added. */
export type RuntimeEventType = RuntimeEvent["type"];

export type TranscriptEvent = Extract<
	RuntimeEvent,
	{
		type:
			| "turn_start"
			| "turn_end"
			| "token"
			| "thinking_token"
			| "message_update"
			| "message_reasoning_update"
			| "notice"
			| "tool_call_start"
			| "tool_call_update"
			| "tool_call_id_update"
			| "tool_execution_start"
			| "tool_execution_update"
			| "tool_execution_end"
			| "subagent_chunk"
			| "subagent_lifecycle";
	}
>;

export function isTranscriptEvent(
	event: RuntimeEvent,
): event is TranscriptEvent {
	switch (event.type) {
		case "turn_start":
		case "turn_end":
		case "token":
		case "thinking_token":
		case "message_update":
		case "message_reasoning_update":
		case "notice":
		case "tool_call_start":
		case "tool_call_update":
		case "tool_call_id_update":
		case "tool_execution_start":
		case "tool_execution_update":
		case "tool_execution_end":
		case "subagent_chunk":
		case "subagent_lifecycle":
			return true;
		default:
			return false;
	}
}
