// ── edit tool ────────────────────────────────────────────────────────────────────
// Edit file contents with exact text replacement. Supports both single old_text/new_text
// and multi-edit arrays, plus replaceAll for renames. Matching (exact, then fuzzy) runs
// through @logician/log-natives' pi_edit engine (oh-my-pi's "replace" mode) rather than a
// local reimplementation — the same engine that ports pi's own edit tool. BOM handling and
// line-ending preservation happen inside that engine.

import { createHash } from "node:crypto";
import { homedir } from "node:os";
import type { MutationReceipt, Tool, ToolResult } from "@logician/log-core";
import {
	createMutationSession,
	type MutationProposal,
	mutationReceipt,
} from "./mutation/session.js";
import { checkFileParse } from "./support/auto-repair.js";
import { createEditStore } from "./support/edit-store.js";
import { executeHashlineEdit } from "./support/hashline-engine.js";
import { withFileMutationQueue } from "./support/mutation-queue.js";
import {
	hasBeenRead,
	isStaleSinceRead,
	refreshAfterWrite,
} from "./support/read-tracker.ts";
import { generateEditDiffs } from "./support/utils/diff-utils.ts";
import { defaultEditOperations } from "./support/utils/helpers.ts";
import {
	ensureInsideCwd,
	resolveReadPath,
} from "./support/utils/path-utils.ts";

export interface Edit {
	oldText: string;
	newText: string;
	replaceAll?: boolean;
}

// ============================================================================
// Native edit engine (pi_edit "replace" mode)
// ============================================================================

type NativeModule = typeof import("@logician/log-natives");

let nativePromise: Promise<NativeModule> | undefined;

/** Load the native addon lazily so a missing/unbuilt build only breaks callers who need it. */
function loadNative(): Promise<NativeModule> {
	if (!nativePromise) {
		nativePromise = import("@logician/log-natives").catch(error => {
			nativePromise = undefined;
			throw new Error(
				`@logician/log-natives addon not available (run \`bun run build\` in packages/log-natives): ${
					error instanceof Error ? error.message : String(error)
				}`,
			);
		});
	}
	return nativePromise;
}

interface NativeEditOutcome {
	/** Unified diff for the one file this call touched; "" for a no-op or error. */
	diff: string;
	/** Full before/after text (both "" for a no-op or error). */
	baseContent: string;
	newContent: string;
	/** Set when the engine reported a match/parse/write failure. */
	error?: string;
	mutation: MutationReceipt;
}

/**
 * Run a batch of oldText/newText edits against `resolved` through pi_edit's
 * "replace" engine (exact match, then fuzzy above a high similarity
 * threshold) and apply the result through the existing MutationSession — the
 * native engine only computes *what* the new content should be; disk I/O,
 * staleness re-checks, and receipts stay exactly as they were before.
 */
async function runNativeReplaceEdit(
	resolved: string,
	edits: Edit[],
	cwd: string,
	mutation: ReturnType<typeof createMutationSession>,
): Promise<NativeEditOutcome> {
	const native = await loadNative();
	const store = new native.EditStore();
	const session = new native.EditSession(store, {
		cwd,
		mode: "replace",
		allowFuzzy: true,
		// Matches pi_edit's own DEFAULT_FUZZY_THRESHOLD.
		fuzzyThreshold: 0.95,
		enforceSeenLines: false,
		blockAutoGenerated: false,
		planActive: false,
		homeDir: homedir(),
		rawInput: false,
	});
	session.setArgsJson(
		JSON.stringify({
			path: resolved,
			edits: edits.map(e => ({
				old_string: e.oldText,
				new_string: e.newText,
				replace_all: e.replaceAll === true,
			})),
		}),
	);
	session.finish();

	let baseContent = "";
	let newContent = "";
	let mutationResult: Awaited<ReturnType<typeof mutation.apply>> | undefined;
	const emptyReceipt = (error?: string) =>
		mutationReceipt({
			applied: false,
			changed: false,
			path: resolved,
			beforeHash: "",
			afterHash: "",
			linesChanged: 0,
			filesAffected: 0,
			diff: "",
			...(error !== undefined ? { error } : {}),
		});

	try {
		const outcome = await session.apply(
			{ lspFlush: false },
			async (error, request) => {
				if (error) throw error;
				const before = await defaultEditOperations
					.readFile(request.path)
					.then(buf => buf.toString("utf-8"))
					.catch(() => "");
				const after = request.content ?? "";
				const proposal: MutationProposal = {
					path: request.path,
					before,
					beforeHash: createHash("sha256")
						.update(before, "utf-8")
						.digest("hex"),
					after,
					newFile: request.op === "create",
				};
				mutationResult = await mutation.apply(proposal);
				if (mutationResult.error) throw new Error(mutationResult.error);
				baseContent = before;
				newContent = after;
				return { written: after };
			},
		);

		if (outcome.isError) {
			return {
				diff: "",
				baseContent: "",
				newContent: "",
				error: outcome.text,
				mutation: mutationResult
					? mutationReceipt(mutationResult)
					: emptyReceipt(outcome.text),
			};
		}

		if (!mutationResult) {
			// The engine staged nothing to write: a real no-op (new content
			// matched the old content byte-for-byte).
			return {
				diff: "",
				baseContent: "",
				newContent: "",
				mutation: emptyReceipt(),
			};
		}

		return {
			diff: generateEditDiffs(resolved, baseContent, newContent).diff,
			baseContent,
			newContent,
			mutation: mutationReceipt(mutationResult),
		};
	} finally {
		session.close();
	}
}

// ============================================================================
// Errors
// ============================================================================

function combineMutationReceipts(receipts: MutationReceipt[]): MutationReceipt {
	return {
		kind: "mutation",
		applied: receipts.some(receipt => receipt.applied),
		changed: receipts.some(receipt => receipt.changed),
		paths: receipts.flatMap(receipt => receipt.paths),
		filesAffected: receipts.reduce(
			(total, receipt) => total + receipt.filesAffected,
			0,
		),
		revisions: receipts.flatMap(receipt => receipt.revisions),
		error: receipts.find(receipt => receipt.error)?.error,
	};
}

// ============================================================================
// Schema & argument normalization
// ============================================================================

const editSchema = {
	type: "object",
	properties: {
		path: {
			type: "string",
			description: "File path to edit (relative or absolute)",
		},
		edits: {
			type: "array",
			description:
				"Exact text replacements. Each must match a unique, " +
				"non-overlapping region of the original file. " +
				"If two changes touch the same block, merge them into one edit.",
			items: {
				type: "object",
				properties: {
					oldText: {
						type: "string",
						description: "Exact text to find and replace",
					},
					newText: { type: "string", description: "Replacement text" },
					replaceAll: {
						type: "boolean",
						description:
							"Replace every occurrence of oldText instead of requiring uniqueness. " +
							"Use for renaming a symbol throughout the file.",
					},
				},
			},
		},
		input: {
			type: "string",
			description:
				"Hashline-format edit input (alternative to edits[]). " +
				"Use [path#4hex] file headers with PUT/CUT/MV/REM operations. " +
				"When provided alongside edits[], the input field takes precedence.",
		},
	},
	required: ["path"],
} as const;
function prepareArguments(raw: unknown): Record<string, unknown> {
	if (!raw || typeof raw !== "object" || Array.isArray(raw)) return {};
	const args = raw as Record<string, unknown>;

	const path =
		(typeof args.path === "string" && args.path) ||
		(typeof args.file_path === "string" && args.file_path) ||
		"";

	const oldText =
		(typeof args.oldText === "string" && args.oldText) ||
		(typeof args.old_text === "string" && args.old_text) ||
		(typeof args.oldString === "string" && args.oldString) ||
		"";
	const newText =
		(typeof args.newText === "string" && args.newText) ||
		(typeof args.new_text === "string" && args.new_text) ||
		(typeof args.newString === "string" && args.newString) ||
		"";
	const topReplaceAll = args.replaceAll === true || args.replace_all === true;

	let rawEdits = args.edits;
	if (typeof rawEdits === "string") {
		try {
			const parsed = JSON.parse(rawEdits);
			if (Array.isArray(parsed)) rawEdits = parsed;
		} catch (_e: unknown) {
			// Leave as-is
		}
	}

	const edits: Edit[] = [];
	if (oldText) {
		edits.push({ oldText, newText, replaceAll: topReplaceAll });
	}
	if (Array.isArray(rawEdits)) {
		for (const item of rawEdits) {
			if (!item || typeof item !== "object") continue;
			const e = item as Record<string, unknown>;
			const eOld =
				(typeof e.oldText === "string" && e.oldText) ||
				(typeof e.old_text === "string" && e.old_text) ||
				"";
			const eNew =
				(typeof e.newText === "string" && e.newText) ||
				(typeof e.new_text === "string" && e.new_text) ||
				"";
			if (eOld) {
				edits.push({
					oldText: eOld,
					newText: eNew,
					replaceAll: e.replaceAll === true || e.replace_all === true,
				});
			}
		}
	}

	const input =
		typeof args.input === "string" && args.input ? args.input : undefined;
	return { path, edits, input };
}

// ============================================================================
// Tool definition
// ============================================================================

export const edit: Tool = {
	name: "edit",
	executionMode: "parallel",
	label: "Edit File",
	hookAliases: ["Edit"],
	description:
		"Edit a single file using exact text replacement, anchored by a content-hash read of the file. " +
		"Every edits[].oldText must match a unique, " +
		"non-overlapping region of the original file " +
		"(or set replaceAll: true on an edit to replace every occurrence). " +
		"The file must have been read with read first; a stale anchor (file changed since that read) is detected and rejected. " +
		"Supports BOM handling and line-ending preservation.",
	promptSnippet:
		"Edit files using exact text replacement with precise matching",
	promptGuidelines: [
		"Use edit for surgical edits; keep oldText unique in the file, or set replaceAll for renames",
	],
	parameters: editSchema,
	prepareArguments,
	execute: async (
		args: Record<string, unknown>,
		ctx,
	): Promise<string | ToolResult> => {
		const path = String(args.path ?? "");
		const edits = (args.edits as Edit[]) || [];
		const input = String(args.input ?? "");

		if (!path) {
			return "Error: edit requires a path.";
		}

		if (input && edits.length > 0)
			return "Error: Use either input or text edits, not both.";
		if (!input && edits.length === 0) {
			return "Error: Provide oldText/newText or edits[].";
		}
		const resolved = resolveReadPath(path, ctx.cwd || process.cwd());
		ensureInsideCwd(ctx.cwd, resolved, ctx.allowedPaths, ctx.allowAllPaths);

		try {
			await defaultEditOperations.access(resolved);
		} catch (error: unknown) {
			const errorMessage =
				error instanceof Error && "code" in error
					? `Error code: ${(error as { code: string }).code}`
					: String(error);
			return `Could not edit file: ${path}. ${errorMessage}.`;
		}

		if (!hasBeenRead(resolved)) {
			return (
				`${resolved} has not been read yet. ` +
				"Read it with read before editing."
			);
		}
		const store = createEditStore();
		const mutation = createMutationSession(store, ctx.cwd || process.cwd(), {
			allowedPaths: ctx.allowedPaths,
			allowAllPaths: ctx.allowAllPaths,
		});

		return withFileMutationQueue(resolved, async () => {
			if (isStaleSinceRead(resolved)) {
				return (
					`${resolved} has been modified since it was last read. ` +
					"Read it again before editing."
				);
			}
			if (input) {
				const result = await executeHashlineEdit(
					input,
					store,
					mutation,
					ctx.cwd || process.cwd(),
					resolved,
				);
				const receipt = combineMutationReceipts(result.receipts ?? []);
				if (result.error)
					return {
						content: `Error: ${result.error}`,
						isError: true,
						details: { mutation: receipt },
					};
				if (!result.applied) {
					const noopWarning = store.recordNoop(resolved);
					if (noopWarning)
						return { content: noopWarning, details: { mutation: receipt } };
					return {
						content:
							"No changes made: hashline edits matched the current content.",
						details: { mutation: receipt },
					};
				}
				store.recordSuccess(resolved);
				refreshAfterWrite(resolved);
				// Auto-recovery: check parse after edit
				const hashlineParseError = await checkFileParse(resolved);
				if (hashlineParseError) {
					return {
						content:
							`Applied ${result.linesChanged} line change(s) across ${result.filesAffected} file(s).\n` +
							`\n⚠ Parse error detected after edit: ${hashlineParseError}` +
							(result.diff ? `\n\nDiff:\n${result.diff}` : ""),
						isError: true,
						details: {
							mutation: receipt,
							diff: result.diff,
							linesChanged: result.linesChanged,
							filesAffected: result.filesAffected,
							parseError: true,
						},
					};
				}
				return {
					content:
						`Applied ${result.linesChanged} line change(s) across ${result.filesAffected} file(s).` +
						(result.diff ? `\n\nDiff:\n${result.diff}` : ""),
					details: {
						mutation: receipt,
						diff: result.diff,
						linesChanged: result.linesChanged,
						filesAffected: result.filesAffected,
					},
				};
			}
			const native = await runNativeReplaceEdit(
				resolved,
				edits,
				ctx.cwd || process.cwd(),
				mutation,
			);
			refreshAfterWrite(resolved);

			if (native.error)
				return {
					content: `Error: ${native.error}`,
					isError: true,
					details: { mutation: native.mutation },
				};
			if (!native.mutation.changed) {
				const noopWarning = store.recordNoop(resolved);
				if (noopWarning)
					return {
						content: noopWarning,
						details: { mutation: native.mutation },
					};
				return {
					content: "No changes made: the edit produced identical content.",
					details: { mutation: native.mutation },
				};
			}
			store.recordSuccess(resolved);

			// Auto-recovery: check parse after edit
			const parseError = await checkFileParse(resolved);
			if (parseError) {
				return {
					content:
						`Successfully replaced ${edits.length} block(s) in ${path}.` +
						`\n\n⚠ Parse error detected after edit: ${parseError}` +
						(native.diff ? `\n\nDiff:\n${native.diff}` : ""),
					isError: true,
					details: {
						mutation: native.mutation,
						diff: native.diff,
						parseError: true,
					},
				};
			}

			return {
				content:
					`Successfully replaced ${edits.length} block(s) in ${path}.\n` +
					(native.diff ? `\n\nDiff:\n${native.diff}` : ""),
				details: {
					mutation: native.mutation,
					diff: native.diff,
				},
			};
		});
	},
};
