// ── edit tool ────────────────────────────────────────────────────────────────────
// Edit file contents with exact text replacement. Supports both single old_text/new_text
// and multi-edit arrays, plus replaceAll for renames. Matching (exact, then fuzzy) runs
// through @logician/log-natives' pi_edit engine (oh-my-pi's "replace" mode) rather than a
// local reimplementation — the same engine that ports pi's own edit tool. BOM handling and
// line-ending preservation happen inside that engine.

import { createHash } from "node:crypto";
import { homedir } from "node:os";
import * as path from "node:path";
import type { MutationReceipt, Tool, ToolResult } from "@logician/log-core";
import {
	createMutationSession,
	type MutationProposal,
	mutationReceipt,
} from "./mutation/session.js";
import { checkFileParse } from "./support/auto-repair.js";
import { createEditStore } from "./support/edit-store.js";
import { withFileMutationQueue } from "./support/mutation-queue.js";
import { getNativeEditStore, loadNative } from "./support/native-addon.ts";
import {
	hasBeenRead,
	isStaleSinceRead,
	refreshAfterWrite,
} from "./support/read-tracker.ts";
import { generateEditDiffs } from "./support/utils/diff-utils.ts";
import { defaultEditOperations } from "./support/utils/helpers.ts";
import {
	ensureInsideCwd,
	resolveReadPath,
} from "./support/utils/path-utils.ts";

export interface Edit {
	oldText: string;
	newText: string;
	replaceAll?: boolean;
}

// ============================================================================
// Native edit engine (pi_edit "replace" and "hashline" modes)
// ============================================================================

interface NativeEditOutcome {
	/** Unified diff for the one file this call touched; "" for a no-op or error. */
	diff: string;
	/** Full before/after text (both "" for a no-op or error). */
	baseContent: string;
	newContent: string;
	/** Set when the engine reported a match/parse/write failure. */
	error?: string;
	mutation: MutationReceipt;
}

/**
 * Run a batch of oldText/newText edits against `resolved` through pi_edit's
 * "replace" engine (exact match, then fuzzy above a high similarity
 * threshold) and apply the result through the existing MutationSession — the
 * native engine only computes *what* the new content should be; disk I/O,
 * staleness re-checks, and receipts stay exactly as they were before.
 */
async function runNativeReplaceEdit(
	resolved: string,
	edits: Edit[],
	cwd: string,
	mutation: ReturnType<typeof createMutationSession>,
): Promise<NativeEditOutcome> {
	const native = await loadNative();
	const store = new native.EditStore();
	const session = new native.EditSession(store, {
		cwd,
		mode: "replace",
		allowFuzzy: true,
		// Matches pi_edit's own DEFAULT_FUZZY_THRESHOLD.
		fuzzyThreshold: 0.95,
		enforceSeenLines: false,
		blockAutoGenerated: false,
		planActive: false,
		homeDir: homedir(),
		rawInput: false,
	});
	session.setArgsJson(
		JSON.stringify({
			path: resolved,
			edits: edits.map(e => ({
				old_string: e.oldText,
				new_string: e.newText,
				replace_all: e.replaceAll === true,
			})),
		}),
	);
	session.finish();

	let baseContent = "";
	let newContent = "";
	let mutationResult: Awaited<ReturnType<typeof mutation.apply>> | undefined;
	const emptyReceipt = (error?: string) =>
		mutationReceipt({
			applied: false,
			changed: false,
			path: resolved,
			beforeHash: "",
			afterHash: "",
			linesChanged: 0,
			filesAffected: 0,
			diff: "",
			...(error !== undefined ? { error } : {}),
		});

	try {
		const outcome = await session.apply(
			{ lspFlush: false },
			async (error, request) => {
				if (error) throw error;
				const before = await defaultEditOperations
					.readFile(request.path)
					.then(buf => buf.toString("utf-8"))
					.catch(() => "");
				const after = request.content ?? "";
				const proposal: MutationProposal = {
					path: request.path,
					before,
					beforeHash: createHash("sha256")
						.update(before, "utf-8")
						.digest("hex"),
					after,
					newFile: request.op === "create",
				};
				mutationResult = await mutation.apply(proposal);
				if (mutationResult.error) throw new Error(mutationResult.error);
				baseContent = before;
				newContent = after;
				return { written: after };
			},
		);

		if (outcome.isError) {
			return {
				diff: "",
				baseContent: "",
				newContent: "",
				error: outcome.text,
				mutation: mutationResult
					? mutationReceipt(mutationResult)
					: emptyReceipt(outcome.text),
			};
		}

		if (!mutationResult) {
			// The engine staged nothing to write: a real no-op (new content
			// matched the old content byte-for-byte).
			return {
				diff: "",
				baseContent: "",
				newContent: "",
				mutation: emptyReceipt(),
			};
		}

		return {
			diff: (await generateEditDiffs(resolved, baseContent, newContent)).diff,
			baseContent,
			newContent,
			mutation: mutationReceipt(mutationResult),
		};
	} finally {
		session.close();
	}
}

interface NativeHashlineOutcome {
	applied: boolean;
	linesChanged: number;
	filesAffected: number;
	diff: string;
	error?: string;
	receipts: MutationReceipt[];
}

const HASHLINE_HEADER_RE = /^\[(.+)#[a-fA-F0-9]{4}\]$/;

/**
 * The native hashline grammar allows one document to carry multiple
 * `[path#tag]` sections (e.g. a cross-file register move), operating on
 * whatever path each header names — it never checks that against the tool
 * call's own `path` argument. This tool still presents a single-file
 * contract (one required `path`, and the read-tracking/no-op bookkeeping
 * below only touches that one `resolved` path), so every header must name
 * that same file; anything else is rejected before it ever reaches the
 * engine, matching the guard the old engine enforced itself.
 */
function assertHashlineHeadersMatch(
	input: string,
	cwd: string,
	resolved: string,
): void {
	for (const line of input.split(/\r?\n/)) {
		const match = HASHLINE_HEADER_RE.exec(line.trim());
		const rawPath = match?.[1];
		if (!rawPath) continue;
		const headerPath = path.resolve(cwd, rawPath);
		if (headerPath !== resolved) {
			throw new Error("Hashline header must target the edit path.");
		}
	}
}

/**
 * Run a hashline document (`[path#tag]` header + PUT/CUT/MV/REM operations)
 * through pi_edit's "hashline" engine. Unlike "replace" mode, hashline
 * validates its `[path#tag]` header against a *recorded* snapshot rather
 * than recomputing a hash from disk, so this requires the same persistent
 * native EditStore that `read` populates — a fresh one would never
 * recognize any tag.
 */
async function runNativeHashlineEdit(
	input: string,
	resolved: string,
	cwd: string,
	mutation: ReturnType<typeof createMutationSession>,
): Promise<NativeHashlineOutcome> {
	try {
		assertHashlineHeadersMatch(input, cwd, resolved);
	} catch (error) {
		return {
			applied: false,
			linesChanged: 0,
			filesAffected: 0,
			diff: "",
			error: error instanceof Error ? error.message : String(error),
			receipts: [],
		};
	}
	const native = await loadNative();
	const store = await getNativeEditStore();
	const session = new native.EditSession(store, {
		cwd,
		mode: "hashline",
		allowFuzzy: false,
		fuzzyThreshold: 0.95,
		enforceSeenLines: false,
		blockAutoGenerated: false,
		planActive: false,
		homeDir: homedir(),
		rawInput: true,
	});
	session.setArgsJson(input);
	session.finish();

	const receipts: MutationReceipt[] = [];
	let linesChanged = 0;
	let filesAffected = 0;

	try {
		const outcome = await session.apply(
			{ lspFlush: false },
			async (error, request) => {
				if (error) throw error;
				const before = await defaultEditOperations
					.readFile(request.path)
					.then(buf => buf.toString("utf-8"))
					.catch(() => "");

				if (request.op === "delete") {
					const result = await mutation.delete(request.path, before);
					receipts.push(mutationReceipt(result));
					if (result.error) throw new Error(result.error);
					filesAffected += result.filesAffected;
					linesChanged += before.split("\n").length;
					return { written: "" };
				}

				if (request.op === "move" && request.moveTo) {
					const after = request.content ?? before;
					if (after === before) {
						const result = await mutation.move(
							request.path,
							request.moveTo,
							before,
						);
						receipts.push(mutationReceipt(result));
						if (result.error) throw new Error(result.error);
						filesAffected += result.filesAffected;
						return { written: after };
					}
					// Rare combined move+content-change: write the destination,
					// then delete the source, as two tracked mutations.
					const created = await mutation.apply({
						path: request.moveTo,
						before: "",
						beforeHash: createHash("sha256").update("", "utf-8").digest("hex"),
						after,
						newFile: true,
					});
					receipts.push(mutationReceipt(created));
					if (created.error) throw new Error(created.error);
					const removed = await mutation.delete(request.path, before);
					receipts.push(mutationReceipt(removed));
					if (removed.error) throw new Error(removed.error);
					filesAffected += created.filesAffected + removed.filesAffected;
					linesChanged += (
						await generateEditDiffs(request.moveTo, before, after)
					).linesChanged;
					return { written: after };
				}

				// create / update
				const after = request.content ?? "";
				const proposal: MutationProposal = {
					path: request.path,
					before,
					beforeHash: createHash("sha256")
						.update(before, "utf-8")
						.digest("hex"),
					after,
					newFile: request.op === "create",
				};
				const result = await mutation.apply(proposal);
				receipts.push(mutationReceipt(result));
				if (result.error) throw new Error(result.error);
				filesAffected += result.filesAffected;
				linesChanged += (await generateEditDiffs(request.path, before, after))
					.linesChanged;
				return { written: after };
			},
		);

		if (outcome.isError) {
			return {
				applied: false,
				linesChanged,
				filesAffected,
				diff: "",
				error: outcome.text,
				receipts,
			};
		}

		return {
			applied: filesAffected > 0,
			linesChanged,
			filesAffected,
			diff: outcome.files.map(file => file.diff).join("\n"),
			receipts,
		};
	} finally {
		session.close();
	}
}

// ============================================================================
// Errors
// ============================================================================

function combineMutationReceipts(receipts: MutationReceipt[]): MutationReceipt {
	return {
		kind: "mutation",
		applied: receipts.some(receipt => receipt.applied),
		changed: receipts.some(receipt => receipt.changed),
		paths: receipts.flatMap(receipt => receipt.paths),
		filesAffected: receipts.reduce(
			(total, receipt) => total + receipt.filesAffected,
			0,
		),
		revisions: receipts.flatMap(receipt => receipt.revisions),
		error: receipts.find(receipt => receipt.error)?.error,
	};
}

// ============================================================================
// Schema & argument normalization
// ============================================================================

/**
 * pi_edit's own hashline spec (`editDescription("hashline")` in
 * @logician/log-natives, ported from oh-my-pi's prompts/hashline.md).
 * Embedded statically rather than loaded at tool-definition time so a
 * missing/unbuilt native addon can't take the whole tool schema down with
 * it — only actually running a hashline edit needs the addon loaded.
 */
const HASHLINE_INPUT_DESCRIPTION = `Line-anchored patch language: name original lines/gaps to replace, insert, cut, or paste; then give new content. \`:\` headers take \`+\` body rows; colonless paste \`PUT\`, \`CUT\`, \`REM\`, \`MV\` take none.

Section header: \`[path#TAG]\` — TAG is the 4-hex snapshot from the latest read/search of that file, required on every section. This tool only edits one file per call: the header must name the same path passed as \`path\`.

Ops:
\`PUT N.=M:\` replaces original inclusive lines N-M with the body. \`PUT N*:\` replaces the syntactic block starting at line N (closing line auto-resolved). \`PUT <N:\` inserts before line N (\`PUT <1:\` = file head); \`PUT >N:\` inserts after line N (\`PUT >$:\` = file tail); \`PUT >N*:\` inserts after block N's end. \`CUT N.=M\` / \`CUT N*\` deletes and captures those lines/block, anonymously or into a named register (\`CUT N.=M @name\`); \`PUT <N @name\` / \`PUT >N @name\` pastes a register at that gap. \`REM\` deletes the file. \`MV dest\` moves/renames it (prior edits in the same section apply to the source; final content lands at dest).

Body rows only follow a \`:\` header: each is a verbatim \`+TEXT\` line (leading whitespace preserved, \`+\` alone is a blank line). There is no \`-old\`/bare/context row — the named range is deleted outright and the body is the complete replacement, so body length has nothing to do with range size. A single line is \`PUT N.=N:\` / \`CUT N.=N\`.

Rules: line numbers and TAGs always come from the latest read/search output and are never renumbered mid-edit — take fresh numbers from the next read or edit response before editing again. Only touch lines that were actually displayed; an elided/unseen line (\`...\`, collapsed \`N-M:\` rows) must be read first. Ranges cover only what changed — never widen a range to include lines you're keeping; separate non-adjacent changes into separate hunks. Named registers persist across edit calls; anonymous ones don't.

Example — read output shows \`[greet.py#A1B2]\` then numbered lines; to rewrite the function body and move the file:
\`\`\`
[greet.py#A1B2]
PUT 1.=3:
+def greet(name):
+    print(f"Hi, {name}")
MV lib/greet.py
\`\`\``;

const editSchema = {
	type: "object",
	properties: {
		path: {
			type: "string",
			description: "File path to edit (relative or absolute)",
		},
		edits: {
			type: "array",
			description:
				"Exact text replacements. Each must match a unique, " +
				"non-overlapping region of the original file. " +
				"If two changes touch the same block, merge them into one edit.",
			items: {
				type: "object",
				properties: {
					oldText: {
						type: "string",
						description: "Exact text to find and replace",
					},
					newText: { type: "string", description: "Replacement text" },
					replaceAll: {
						type: "boolean",
						description:
							"Replace every occurrence of oldText instead of requiring uniqueness. " +
							"Use for renaming a symbol throughout the file.",
					},
				},
			},
		},
		input: {
			type: "string",
			description:
				`${HASHLINE_INPUT_DESCRIPTION}\n\n` +
				"(Alternative to edits[]; when both are provided, input takes precedence.)",
		},
	},
	required: ["path"],
} as const;
function prepareArguments(raw: unknown): Record<string, unknown> {
	if (!raw || typeof raw !== "object" || Array.isArray(raw)) return {};
	const args = raw as Record<string, unknown>;

	const path =
		(typeof args.path === "string" && args.path) ||
		(typeof args.file_path === "string" && args.file_path) ||
		"";

	const oldText =
		(typeof args.oldText === "string" && args.oldText) ||
		(typeof args.old_text === "string" && args.old_text) ||
		(typeof args.oldString === "string" && args.oldString) ||
		"";
	const newText =
		(typeof args.newText === "string" && args.newText) ||
		(typeof args.new_text === "string" && args.new_text) ||
		(typeof args.newString === "string" && args.newString) ||
		"";
	const topReplaceAll = args.replaceAll === true || args.replace_all === true;

	let rawEdits = args.edits;
	if (typeof rawEdits === "string") {
		try {
			const parsed = JSON.parse(rawEdits);
			if (Array.isArray(parsed)) rawEdits = parsed;
		} catch (_e: unknown) {
			// Leave as-is
		}
	}

	const edits: Edit[] = [];
	if (oldText) {
		edits.push({ oldText, newText, replaceAll: topReplaceAll });
	}
	if (Array.isArray(rawEdits)) {
		for (const item of rawEdits) {
			if (!item || typeof item !== "object") continue;
			const e = item as Record<string, unknown>;
			const eOld =
				(typeof e.oldText === "string" && e.oldText) ||
				(typeof e.old_text === "string" && e.old_text) ||
				"";
			const eNew =
				(typeof e.newText === "string" && e.newText) ||
				(typeof e.new_text === "string" && e.new_text) ||
				"";
			if (eOld) {
				edits.push({
					oldText: eOld,
					newText: eNew,
					replaceAll: e.replaceAll === true || e.replace_all === true,
				});
			}
		}
	}

	const input =
		typeof args.input === "string" && args.input ? args.input : undefined;
	return { path, edits, input };
}

// ============================================================================
// Tool definition
// ============================================================================

export const edit: Tool = {
	name: "edit",
	executionMode: "parallel",
	label: "Edit File",
	hookAliases: ["Edit"],
	description:
		"Edit a single file using exact text replacement, anchored by a content-hash read of the file. " +
		"Every edits[].oldText must match a unique, " +
		"non-overlapping region of the original file " +
		"(or set replaceAll: true on an edit to replace every occurrence). " +
		"The file must have been read with read first; a stale anchor (file changed since that read) is detected and rejected. " +
		"Supports BOM handling and line-ending preservation.",
	promptSnippet:
		"Edit files using exact text replacement with precise matching",
	promptGuidelines: [
		"Use edit for surgical edits; keep oldText unique in the file, or set replaceAll for renames",
	],
	parameters: editSchema,
	prepareArguments,
	execute: async (
		args: Record<string, unknown>,
		ctx,
	): Promise<string | ToolResult> => {
		const path = String(args.path ?? "");
		const edits = (args.edits as Edit[]) || [];
		const input = String(args.input ?? "");

		if (!path) {
			return "Error: edit requires a path.";
		}

		if (input && edits.length > 0)
			return "Error: Use either input or text edits, not both.";
		if (!input && edits.length === 0) {
			return "Error: Provide oldText/newText or edits[].";
		}
		const resolved = resolveReadPath(path, ctx.cwd || process.cwd());
		ensureInsideCwd(ctx.cwd, resolved, ctx.allowedPaths, ctx.allowAllPaths);

		try {
			await defaultEditOperations.access(resolved);
		} catch (error: unknown) {
			const errorMessage =
				error instanceof Error && "code" in error
					? `Error code: ${(error as { code: string }).code}`
					: String(error);
			return `Could not edit file: ${path}. ${errorMessage}.`;
		}

		if (!hasBeenRead(resolved)) {
			return (
				`${resolved} has not been read yet. ` +
				"Read it with read before editing."
			);
		}
		const store = createEditStore();
		const mutation = createMutationSession(store, ctx.cwd || process.cwd(), {
			allowedPaths: ctx.allowedPaths,
			allowAllPaths: ctx.allowAllPaths,
		});

		return withFileMutationQueue(resolved, async () => {
			if (isStaleSinceRead(resolved)) {
				return (
					`${resolved} has been modified since it was last read. ` +
					"Read it again before editing."
				);
			}
			if (input) {
				const result = await runNativeHashlineEdit(
					input,
					resolved,
					ctx.cwd || process.cwd(),
					mutation,
				);
				const receipt = combineMutationReceipts(result.receipts);
				if (result.error)
					return {
						content: `Error: ${result.error}`,
						isError: true,
						details: { mutation: receipt },
					};
				if (!result.applied) {
					const noopWarning = store.recordNoop(resolved);
					if (noopWarning)
						return { content: noopWarning, details: { mutation: receipt } };
					return {
						content:
							"No changes made: hashline edits matched the current content.",
						details: { mutation: receipt },
					};
				}
				store.recordSuccess(resolved);
				refreshAfterWrite(resolved);
				// Auto-recovery: check parse after edit
				const hashlineParseError = await checkFileParse(resolved);
				if (hashlineParseError) {
					return {
						content:
							`Applied ${result.linesChanged} line change(s) across ${result.filesAffected} file(s).\n` +
							`\n⚠ Parse error detected after edit: ${hashlineParseError}` +
							(result.diff ? `\n\nDiff:\n${result.diff}` : ""),
						isError: true,
						details: {
							mutation: receipt,
							diff: result.diff,
							linesChanged: result.linesChanged,
							filesAffected: result.filesAffected,
							parseError: true,
						},
					};
				}
				return {
					content:
						`Applied ${result.linesChanged} line change(s) across ${result.filesAffected} file(s).` +
						(result.diff ? `\n\nDiff:\n${result.diff}` : ""),
					details: {
						mutation: receipt,
						diff: result.diff,
						linesChanged: result.linesChanged,
						filesAffected: result.filesAffected,
					},
				};
			}
			const native = await runNativeReplaceEdit(
				resolved,
				edits,
				ctx.cwd || process.cwd(),
				mutation,
			);
			refreshAfterWrite(resolved);

			if (native.error)
				return {
					content: `Error: ${native.error}`,
					isError: true,
					details: { mutation: native.mutation },
				};
			if (!native.mutation.changed) {
				const noopWarning = store.recordNoop(resolved);
				if (noopWarning)
					return {
						content: noopWarning,
						details: { mutation: native.mutation },
					};
				return {
					content: "No changes made: the edit produced identical content.",
					details: { mutation: native.mutation },
				};
			}
			store.recordSuccess(resolved);

			// Auto-recovery: check parse after edit
			const parseError = await checkFileParse(resolved);
			if (parseError) {
				return {
					content:
						`Successfully replaced ${edits.length} block(s) in ${path}.` +
						`\n\n⚠ Parse error detected after edit: ${parseError}` +
						(native.diff ? `\n\nDiff:\n${native.diff}` : ""),
					isError: true,
					details: {
						mutation: native.mutation,
						diff: native.diff,
						parseError: true,
					},
				};
			}

			return {
				content:
					`Successfully replaced ${edits.length} block(s) in ${path}.\n` +
					(native.diff ? `\n\nDiff:\n${native.diff}` : ""),
				details: {
					mutation: native.mutation,
					diff: native.diff,
				},
			};
		});
	},
};
