// ── Bridge event types ─────────────────────────────────────────────────────────
// Mirrors logician_bridge.py's _emit() protocol

export type BridgeEventType =
	// Agent lifecycle
	| "agent_start"
	| "agent_end"
	// Retry / error observability
	| "agent_retry_start"
	| "agent_retry_end"
	| "agent_error"
	// Turn lifecycle
	| "turn_start"
	| "turn_end"
	// Token streaming
	| "token"
	| "thinking_token"
	// Granular text streaming boundaries
	| "text_start"
	| "text_end"
	// Message update (full partial assistant message)
	| "message_update"
	// Message start (before assistant response, for steering detection)
	| "message_start"
	// Queue update (steering + follow-up)
	| "queue_update"
	// Tool execution
	| "tool_start"
	| "tool_end"
	| "tool_execution_start"
	| "tool_execution_update"
	| "tool_execution_end"
	// Steering
	// Guardrail/repair
	| "repair_nudge"
	// UI state
	| "phase"
	| "context_update"
	| "compaction"
	| "memory_update"
	// Agent question / interactive prompt
	| "question_request"
	// Session lifecycle
	| "session_delete"
	| "message_end"
	| "agent_settled"
	| "model_select";

export interface MemoryUpdateEvent {
	type: "memory_update";
	kind:
		| "observations_added"
		| "reflections_added"
		| "reflections_evolved"
		| "observations_dropped"
		| "cleared";
	count: number;
	items?: Array<{ id: string; content: string; relevance?: string }>;
}

// ── Parsed event shapes ───────────────────────────────────────────────────────

export interface TokenEvent {
	type: "token";
	token: string;
}

export interface ThinkingTokenEvent {
	type: "thinking_token";
	token: string;
}

export interface MessageStartEvent {
	type: "message_start";
	turnId: string;
	role: string;
}

export interface MessageEndEvent {
	type: "message_end";
	turnId: string;
	message?: { role: string; content: string };
}

export interface TextStartEvent {
	type: "text_start";
	turnId: string;
}

export interface TextEndEvent {
	type: "text_end";
	turnId: string;
}

export interface MessageUpdateEvent {
	type: "message_update";
	turnId: string;
	message: {
		role: string;
		content: string | null;
		tool_calls?: Array<{
			id: string;
			name: string;
			arguments: string;
		}>;
	};
}

export interface TurnStartEvent {
	type: "turn_start";
	turn_id: string;
}

export interface TurnEndEvent {
	type: "turn_end";
	turn_id: string;
	message: string;
	final_message?: MessageUpdateEvent["message"];
}

export interface ToolStartEvent {
	type: "tool_start" | "tool_execution_start";
	tool_name: string;
	tool_args?: Record<string, unknown>;
	turn_id?: string;
	tool_call_id?: string;
}

export interface ToolEndEvent {
	type: "tool_end" | "tool_execution_end";
	tool_name: string;
	result?: string;
	is_error?: boolean;
	turn_id?: string;
	tool_call_id?: string;
	// Structured metadata the tool returned alongside its text result.
	details?: Record<string, unknown>;
}

export interface ToolUpdateEvent {
	type: "tool_execution_update";
	tool_name: string;
	partial_result?: string;
	update_kind?: "arguments" | "output";
	turn_id?: string;
	tool_call_id?: string;
}

export interface PhaseEvent {
	type: "phase";
	state: string;
	note?: string;
}

export interface ContextUpdateEvent {
	type: "context_update";
	tokens: number;
	max_tokens?: number;
	compacted?: boolean;
	/** null means the provider supplied no cache telemetry. */
	cached_tokens?: number | null;
	/** Tokens sent to the provider (prompt/input); null means unavailable. */
	prompt_tokens?: number | null;
	/** Tokens generated by the provider (completion/output); null means unavailable. */
	completion_tokens?: number | null;
}

export interface CompactionEvent {
	type: "compaction";
	reason: string;
	tokens_before?: number;
	tokens_after?: number;
}

export interface RepairEvent {
	type: "repair_nudge";
	turn_id?: string;
	repair_stage?: string;
	attempt?: number;
	tool_name?: string;
	error_type?: string;
	message?: string;
}

export interface TodosEvent {
	type: "todos";
	todos: Array<{
		id: number;
		subject: string;
		description?: string;
		activeForm?: string;
		status: "pending" | "in_progress" | "completed" | "deleted";
		blockedBy?: number[];
		owner?: string;
		metadata?: Record<string, unknown>;
	}>;
}

export interface SteeredEvent {
	type: "steered";
	message: string;
}

export interface QueueUpdateEvent {
	type: "queue_update";
	steering: string[];
	followUp: string[];
	nextTurn?: string[];
}

export interface ModelSelectEvent {
	type: "model_select";
	model: string;
}

// Agent lifecycle
export interface AgentStartEvent {
	type: "agent_start";
	iteration?: number;
}

export interface AgentEndEvent {
	type: "agent_end";
	messages?: Array<{ role: string; content: string }>;
	outcome?: {
		status: "completed" | "needs_input" | "blocked" | "failed" | "cancelled";
		summary?: string;
		source: "structured" | "heuristic" | "runtime";
	};
}

export interface AgentSettledEvent {
	type: "agent_settled";
	nextTurnCount?: number;
}

// Retry / error observability
export interface AgentRetryStartEvent {
	type: "agent_retry_start";
	attempt: number;
	maxRetries: number;
	delayMs: number;
	error: string;
	reason?: "compaction" | "error" | "overflow" | "rate_limit";
}

export interface AgentRetryEndEvent {
	type: "agent_retry_end";
	attempt: number;
	success: boolean;
	reason?: "compaction" | "error" | "overflow" | "rate_limit";
}

export interface AgentErrorEvent {
	type: "agent_error";
	message: string;
	phase: "model" | "tool" | "compaction" | "network" | "other";
	recoverable: boolean;
}

// Session lifecycle
export interface SessionDeleteEvent {
	type: "session_delete";
	sessionFile: string;
	sessionId: string;
}

// A standalone status line (retry / error / model / stopped) rendered as its
// own iconed, coloured chunk rather than folded into assistant prose.
export interface NoticeEvent {
	type: "notice";
	level: "info" | "warn" | "error" | "success";
	label: string;
	text: string;
}

// One ordered chunk of a subagent's activity — thinking/response text or a
// tool call — carrying the child event's own emit-time sequence number so the
// transcript can interleave text and tool calls in true chronological order,
// the same way the parent agent's own AssistantChunk stream is interleaved.
export type SubagentChunkEvent =
	| {
			type: "subagent_chunk";
			agentId: string;
			seq: number;
			kind: "thinking" | "content";
			delta: string;
			taskIndex?: number;
	  }
	| {
			type: "subagent_chunk";
			agentId: string;
			seq: number;
			kind: "tool_start";
			toolCallId: string;
			toolName: string;
			args: string;
			taskIndex?: number;
	  }
	| {
			type: "subagent_chunk";
			agentId: string;
			seq: number;
			kind: "tool_end";
			toolCallId: string;
			toolName: string;
			result: string;
			isError: boolean;
			taskIndex?: number;
	  };

// Structured start/end lifecycle for one subagent run, carrying its taskIndex
// when spawned as part of a spawn_agents batch — the single source of truth
// for per-task status, replacing the old streamOutput marker-string protocol
// (`▶ N agent` / `✓ N agent` / `× N agent`).
export type SubagentLifecycleEvent =
	| {
			type: "subagent_lifecycle";
			phase: "start";
			agentId: string;
			agent: string;
			task: string;
			taskIndex?: number;
	  }
	| {
			type: "subagent_lifecycle";
			phase: "end";
			agentId: string;
			agent: string;
			result: string;
			isError: boolean;
			turns?: number;
			taskIndex?: number;
	  };

// A tool call is paused waiting for the user's allow/deny decision. The UI
// answers via bridge.respondToPermission(tool_call_id, decision).
export interface PermissionRequestEvent {
	type: "permission_request";
	tool_name: string;
	tool_call_id: string;
	args: Record<string, unknown>;
}

export interface QuestionRequestEvent {
	type: "question_request";
	question_id: string;
	questions: Array<{
		id: string;
		header?: string;
		question: string;
		choices: Array<{ value: string; label: string; description?: string }>;
	}>;
}

// Fired after every completed turn — a safe rewind point exists and the
// conversation has been persisted. Use to show autosave indicators.
export interface SavePointEvent {
	type: "save_point";
}

export type ParsedBridgeEvent =
	| AgentStartEvent
	| AgentEndEvent
	| AgentSettledEvent
	| TokenEvent
	| ThinkingTokenEvent
	| TextStartEvent
	| TextEndEvent
	| MessageUpdateEvent
	| TurnStartEvent
	| TurnEndEvent
	| ToolStartEvent
	| ToolUpdateEvent
	| ToolEndEvent
	| MessageStartEvent
	| MessageEndEvent
	| QueueUpdateEvent
	| PhaseEvent
	| ContextUpdateEvent
	| CompactionEvent
	| RepairEvent
	| TodosEvent
	| SteeredEvent
	| ModelSelectEvent
	| NoticeEvent
	| SubagentChunkEvent
	| SubagentLifecycleEvent
	| PermissionRequestEvent
	| QuestionRequestEvent
	| MemoryUpdateEvent
	| SavePointEvent
	| AgentRetryStartEvent
	| AgentRetryEndEvent
	| AgentErrorEvent
	| SessionDeleteEvent;

// ── Bridge commands (TUI → bridge) ────────────────────────────────────────────

export type BridgeCommand =
	| { type: "message"; message: string }
	| { type: "slash"; command: string; args: string }
	| { type: "cancel" }
	| { type: "thinking"; level: string }
	| { type: "cache"; action: string }
	| { type: "reset" }
	| { type: "config"; key: string; value: unknown };
