[package]
name = "pi-natives"
version.workspace = true
edition.workspace = true
license = "MIT"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
ast-grep-core.workspace = true
flume.workspace = true
globset.workspace = true
heapless.workspace = true
inferno.workspace = true
napi.workspace = true
napi-derive.workspace = true
parking_lot.workspace = true
pi-ast.workspace = true
pi-edit.workspace = true
pi-walker.workspace = true
smallvec.workspace = true
tokio.workspace = true

[build-dependencies]
napi-build.workspace = true
